<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:n1="http://127.0.0.1:8000/ontology/SUMO.owl#" xmlns:n2="http://127.0.0.1:8000/ontology/Mid-level-ontology.owl#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:service="http://127.0.0.1:8000/services/OWLS-1.1/book_authortext_service.owls" version="2.0">
<xsl:output encoding="iso-8859-1" indent="yes" method="xml" version="1.0"/>
<xsl:template match="/">
<rdf:RDF>
<n1:Text>
<n2:registeredItem>
<n1:Physical>
<n1:hasPurpose>
<n1:Formula>
<n1:ProbabilityFn>
<n1:RealNumber/>
</n1:ProbabilityFn>
<n1:decreasesLikelihood>
<n1:Formula/>
</n1:decreasesLikelihood>
<n1:independentProbability>
<n1:Formula/>
</n1:independentProbability>
<n1:increasesLikelihood>
<n1:Formula/>
</n1:increasesLikelihood>
<n1:modalAttribute>
<n1:NormativeAttribute/>
</n1:modalAttribute>
<n1:entails>
<n1:Formula/>
</n1:entails>
<n1:true>
<n1:TruthValue/>
</n1:true>
</n1:Formula>
</n1:hasPurpose>
<n1:date>
<n1:Day>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
</n1:Day>
</n1:date>
<n1:WhenFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:WhenFn>
<n1:cooccur>
<n1:Physical>
<n1:hasPurpose>
<n1:Formula/>
</n1:hasPurpose>
<n1:date>
<n1:Day/>
</n1:date>
<n1:WhenFn>
<n1:TimeInterval/>
</n1:WhenFn>
<n1:cooccur>
<n1:Physical/>
</n1:cooccur>
<n1:monetaryValue>
<n1:CurrencyMeasure/>
</n1:monetaryValue>
</n1:Physical>
</n1:cooccur>
<n1:monetaryValue>
<n1:CurrencyMeasure>
<n1:MagnitudeFn>
<n1:RealNumber/>
</n1:MagnitudeFn>
</n1:CurrencyMeasure>
</n1:monetaryValue>
</n1:Physical>
</n2:registeredItem>
<n1:version>
<n1:Artifact>
<n1:version>
<n1:Artifact>
<n1:version>
<n1:Artifact/>
</n1:version>
<n2:equipmentType>
<n1:Device/>
</n2:equipmentType>
</n1:Artifact>
</n1:version>
<n2:equipmentType>
<n1:Device>
<n2:powerPlant>
<n1:Artifact/>
</n2:powerPlant>
<n1:version>
<n1:Artifact/>
</n1:version>
<n2:equipmentType>
<n1:Device/>
</n2:equipmentType>
</n1:Device>
</n2:equipmentType>
</n1:Artifact>
</n1:version>
<n2:equipmentType>
<n1:Device>
<n2:powerPlant>
<n1:Artifact>
<n1:version>
<n1:Artifact/>
</n1:version>
<n2:equipmentType>
<n1:Device/>
</n2:equipmentType>
</n1:Artifact>
</n2:powerPlant>
<n1:version>
<n1:Artifact>
<n1:version>
<n1:Artifact/>
</n1:version>
<n2:equipmentType>
<n1:Device/>
</n2:equipmentType>
</n1:Artifact>
</n1:version>
<n2:equipmentType>
<n1:Device>
<n2:powerPlant>
<n1:Artifact/>
</n2:powerPlant>
<n1:version>
<n1:Artifact/>
</n1:version>
<n2:equipmentType>
<n1:Device/>
</n2:equipmentType>
</n1:Device>
</n2:equipmentType>
</n1:Device>
</n2:equipmentType>
<n1:expressedInLanguage>
<n1:Language>
<n1:expressedInLanguage>
<n1:Language>
<n1:expressedInLanguage>
<n1:Language/>
</n1:expressedInLanguage>
</n1:Language>
</n1:expressedInLanguage>
</n1:Language>
</n1:expressedInLanguage>
</n1:Text>
</rdf:RDF>
</xsl:template>
</xsl:transform>
