<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:n1="http://127.0.0.1:8000/ontology/Mid-level-ontology.owl#" xmlns:n2="http://127.0.0.1:8000/ontology/SUMO.owl#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:service="http://127.0.0.1:8000/services/OWLS-1.1/careorganization_diagnosticprocesstimeinterval_service.owls" version="2.0">
<xsl:output encoding="iso-8859-1" indent="yes" method="xml" version="1.0"/>
<xsl:template match="/">
<rdf:RDF>
<n1:CareOrganization>
<n1:yearOfFounding>
<n2:Integer>
<n2:SuccessorFn>
<n2:Integer>
<n2:SuccessorFn>
<n2:Integer/>
</n2:SuccessorFn>
<n2:PredecessorFn>
<n2:Integer/>
</n2:PredecessorFn>
<n1:multiplicativeFactor>
<n2:Integer/>
</n1:multiplicativeFactor>
</n2:Integer>
</n2:SuccessorFn>
<n2:PredecessorFn>
<n2:Integer>
<n2:SuccessorFn>
<n2:Integer/>
</n2:SuccessorFn>
<n2:PredecessorFn>
<n2:Integer/>
</n2:PredecessorFn>
<n1:multiplicativeFactor>
<n2:Integer/>
</n1:multiplicativeFactor>
</n2:Integer>
</n2:PredecessorFn>
<n1:multiplicativeFactor>
<n2:Integer>
<n2:SuccessorFn>
<n2:Integer/>
</n2:SuccessorFn>
<n2:PredecessorFn>
<n2:Integer/>
</n2:PredecessorFn>
<n1:multiplicativeFactor>
<n2:Integer/>
</n1:multiplicativeFactor>
</n2:Integer>
</n1:multiplicativeFactor>
</n2:Integer>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea>
<n1:JudiciaryFn>
<n2:JudicialOrganization>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
</n2:JudicialOrganization>
</n1:JudiciaryFn>
<n1:dependentGeopoliticalArea>
<n2:GeopoliticalArea>
<n1:JudiciaryFn>
<n2:JudicialOrganization/>
</n1:JudiciaryFn>
<n1:dependentGeopoliticalArea>
<n2:GeopoliticalArea/>
</n1:dependentGeopoliticalArea>
<n1:totalGDP>
<n2:CurrencyMeasure/>
</n1:totalGDP>
<n1:CitizenryFn>
<n2:GroupOfPeople/>
</n1:CitizenryFn>
<n2:GovernmentFn>
<n2:Government/>
</n2:GovernmentFn>
<n1:currencyType>
<n2:CurrencyMeasure/>
</n1:currencyType>
<n1:legalSystemType>
<n1:LegalSystemAttribute/>
</n1:legalSystemType>
<n1:primaryGeopoliticalSubdivision>
<n2:GeopoliticalArea/>
</n1:primaryGeopoliticalSubdivision>
<n1:LegislatureFn>
<n1:LegislativeOrganization/>
</n1:LegislatureFn>
<n1:industryOfArea>
<n2:Physical/>
</n1:industryOfArea>
<n1:climateTypeInArea>
<n1:ClimateZone/>
</n1:climateTypeInArea>
<n1:financialAsset>
<n2:Object/>
</n1:financialAsset>
<n2:leader>
<n2:Human/>
</n2:leader>
<n1:economyType>
<n1:EconomicAttribute/>
</n1:economyType>
<n2:editor>
<n2:Text/>
</n2:editor>
<n2:authors>
<n2:Text/>
</n2:authors>
<n2:WealthFn>
<n2:CurrencyMeasure/>
</n2:WealthFn>
<n2:PropertyFn>
<n2:Set/>
</n2:PropertyFn>
<n1:ExecutiveBranchFn>
<n2:Organization/>
</n1:ExecutiveBranchFn>
<n1:customer>
<n2:Corporation/>
</n1:customer>
<n1:governmentType>
<n1:FormOfGovernment/>
</n1:governmentType>
<n1:leaderPosition>
<n2:Position/>
</n1:leaderPosition>
<n1:fiscalYearPeriod>
<n2:TimeInterval/>
</n1:fiscalYearPeriod>
</n2:GeopoliticalArea>
</n1:dependentGeopoliticalArea>
<n1:totalGDP>
<n2:CurrencyMeasure>
<n2:MagnitudeFn>
<n2:RealNumber/>
</n2:MagnitudeFn>
</n2:CurrencyMeasure>
</n1:totalGDP>
<n1:CitizenryFn>
<n2:GroupOfPeople/>
</n1:CitizenryFn>
<n2:GovernmentFn>
<n2:Government/>
</n2:GovernmentFn>
<n1:currencyType>
<n2:CurrencyMeasure>
<n2:MagnitudeFn>
<n2:RealNumber/>
</n2:MagnitudeFn>
</n2:CurrencyMeasure>
</n1:currencyType>
<n1:legalSystemType>
<n1:LegalSystemAttribute/>
</n1:legalSystemType>
<n1:primaryGeopoliticalSubdivision>
<n2:GeopoliticalArea>
<n1:JudiciaryFn>
<n2:JudicialOrganization/>
</n1:JudiciaryFn>
<n1:dependentGeopoliticalArea>
<n2:GeopoliticalArea/>
</n1:dependentGeopoliticalArea>
<n1:totalGDP>
<n2:CurrencyMeasure/>
</n1:totalGDP>
<n1:CitizenryFn>
<n2:GroupOfPeople/>
</n1:CitizenryFn>
<n2:GovernmentFn>
<n2:Government/>
</n2:GovernmentFn>
<n1:currencyType>
<n2:CurrencyMeasure/>
</n1:currencyType>
<n1:legalSystemType>
<n1:LegalSystemAttribute/>
</n1:legalSystemType>
<n1:primaryGeopoliticalSubdivision>
<n2:GeopoliticalArea/>
</n1:primaryGeopoliticalSubdivision>
<n1:LegislatureFn>
<n1:LegislativeOrganization/>
</n1:LegislatureFn>
<n1:industryOfArea>
<n2:Physical/>
</n1:industryOfArea>
<n1:climateTypeInArea>
<n1:ClimateZone/>
</n1:climateTypeInArea>
<n1:financialAsset>
<n2:Object/>
</n1:financialAsset>
<n2:leader>
<n2:Human/>
</n2:leader>
<n1:economyType>
<n1:EconomicAttribute/>
</n1:economyType>
<n2:editor>
<n2:Text/>
</n2:editor>
<n2:authors>
<n2:Text/>
</n2:authors>
<n2:WealthFn>
<n2:CurrencyMeasure/>
</n2:WealthFn>
<n2:PropertyFn>
<n2:Set/>
</n2:PropertyFn>
<n1:ExecutiveBranchFn>
<n2:Organization/>
</n1:ExecutiveBranchFn>
<n1:customer>
<n2:Corporation/>
</n1:customer>
<n1:governmentType>
<n1:FormOfGovernment/>
</n1:governmentType>
<n1:leaderPosition>
<n2:Position/>
</n1:leaderPosition>
<n1:fiscalYearPeriod>
<n2:TimeInterval/>
</n1:fiscalYearPeriod>
</n2:GeopoliticalArea>
</n1:primaryGeopoliticalSubdivision>
<n1:LegislatureFn>
<n1:LegislativeOrganization>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
</n1:LegislativeOrganization>
</n1:LegislatureFn>
<n1:industryOfArea>
<n2:Physical>
<n2:hasPurpose>
<n2:Formula/>
</n2:hasPurpose>
<n2:date>
<n2:Day/>
</n2:date>
<n2:WhenFn>
<n2:TimeInterval/>
</n2:WhenFn>
<n2:cooccur>
<n2:Physical/>
</n2:cooccur>
<n2:monetaryValue>
<n2:CurrencyMeasure/>
</n2:monetaryValue>
</n2:Physical>
</n1:industryOfArea>
<n1:climateTypeInArea>
<n1:ClimateZone>
<n1:climateTypeInArea>
<n1:ClimateZone/>
</n1:climateTypeInArea>
</n1:ClimateZone>
</n1:climateTypeInArea>
<n1:financialAsset>
<n2:Object>
<n2:larger>
<n2:Object/>
</n2:larger>
<n1:deviceState>
<n1:DeviceStateAttribute/>
</n1:deviceState>
<n2:faces>
<n2:DirectionalAttribute/>
</n2:faces>
<n1:older>
<n2:Object/>
</n1:older>
<n2:copy>
<n2:Object/>
</n2:copy>
<n2:uses>
<n2:Agent/>
</n2:uses>
<n2:linked>
<n2:Object/>
</n2:linked>
<n2:exploits>
<n2:Agent/>
</n2:exploits>
<n2:fills>
<n2:Hole/>
</n2:fills>
<n1:orbits>
<n2:AstronomicalBody/>
</n1:orbits>
<n1:barometricPressure>
<n1:AtmosphericPressureMeasure/>
</n1:barometricPressure>
<n2:smaller>
<n2:Object/>
</n2:smaller>
<n1:airTemperature>
<n2:TemperatureMeasure/>
</n1:airTemperature>
<n2:hasPurpose>
<n2:Formula/>
</n2:hasPurpose>
<n2:date>
<n2:Day/>
</n2:date>
<n2:WhenFn>
<n2:TimeInterval/>
</n2:WhenFn>
<n2:cooccur>
<n2:Physical/>
</n2:cooccur>
<n2:monetaryValue>
<n2:CurrencyMeasure/>
</n2:monetaryValue>
</n2:Object>
</n1:financialAsset>
<n2:leader>
<n2:Human>
<n1:intelligenceQuotient>
<n2:RationalNumber/>
</n1:intelligenceQuotient>
<n1:grandfather>
<n2:Man/>
</n1:grandfather>
<n2:citizen>
<n2:Nation/>
</n2:citizen>
<n2:ImmediateFamilyFn>
<n2:FamilyGroup/>
</n2:ImmediateFamilyFn>
<n1:birthday>
<n2:Day/>
</n1:birthday>
<n2:home>
<n2:PermanentResidence/>
</n2:home>
<n1:stepmother>
<n2:Woman/>
</n1:stepmother>
<n1:tenant>
<n2:Residence/>
</n1:tenant>
<n1:occupation>
<n2:FinancialTransaction/>
</n1:occupation>
<n1:groupMember>
<n2:GroupOfPeople/>
</n1:groupMember>
<n1:neighbor>
<n2:Human/>
</n1:neighbor>
<n1:DescendantsFn>
<n2:FamilyGroup/>
</n1:DescendantsFn>
<n1:grandmother>
<n2:Man/>
</n1:grandmother>
<n1:stepfather>
<n2:Man/>
</n1:stepfather>
<n1:cousin>
<n2:Human/>
</n1:cousin>
<n2:stays>
<n2:TemporaryResidence/>
</n2:stays>
<n1:patientMedical>
<n2:CognitiveAgent/>
</n1:patientMedical>
<n1:teacher>
<n2:EducationalOrganization/>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy/>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent/>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object/>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess/>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction/>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent/>
</n1:allegiance>
<n1:disapproves>
<n2:Formula/>
</n1:disapproves>
<n2:wants>
<n2:Physical/>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction/>
</n1:plaintiff>
<n2:knows>
<n2:Formula/>
</n2:knows>
<n2:desires>
<n2:Formula/>
</n2:desires>
<n1:student>
<n2:EducationalOrganization/>
</n1:student>
<n2:considers>
<n2:Formula/>
</n2:considers>
<n1:doubts>
<n2:Formula/>
</n1:doubts>
</n2:Human>
</n2:leader>
<n1:economyType>
<n1:EconomicAttribute/>
</n1:economyType>
<n2:editor>
<n2:Text>
<n1:registeredItem>
<n2:Physical/>
</n1:registeredItem>
<n2:version>
<n2:Artifact/>
</n2:version>
<n1:equipmentType>
<n2:Device/>
</n1:equipmentType>
<n2:expressedInLanguage>
<n2:Language/>
</n2:expressedInLanguage>
</n2:Text>
</n2:editor>
<n2:authors>
<n2:Text>
<n1:registeredItem>
<n2:Physical/>
</n1:registeredItem>
<n2:version>
<n2:Artifact/>
</n2:version>
<n1:equipmentType>
<n2:Device/>
</n1:equipmentType>
<n2:expressedInLanguage>
<n2:Language/>
</n2:expressedInLanguage>
</n2:Text>
</n2:authors>
<n2:WealthFn>
<n2:CurrencyMeasure>
<n2:MagnitudeFn>
<n2:RealNumber/>
</n2:MagnitudeFn>
</n2:CurrencyMeasure>
</n2:WealthFn>
<n2:PropertyFn>
<n2:Set>
<n2:subset>
<n2:Set/>
</n2:subset>
<n2:ComplementFn>
<n2:SetOrClass/>
</n2:ComplementFn>
<n2:GeneralizedIntersectionFn>
<n2:SetOrClass/>
</n2:GeneralizedIntersectionFn>
<n2:GeneralizedUnionFn>
<n2:SetOrClass/>
</n2:GeneralizedUnionFn>
<n2:disjoint>
<n2:SetOrClass/>
</n2:disjoint>
</n2:Set>
</n2:PropertyFn>
<n1:ExecutiveBranchFn>
<n2:Organization>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
<n1:teacher>
<n2:EducationalOrganization/>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy/>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent/>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object/>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess/>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction/>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent/>
</n1:allegiance>
<n1:disapproves>
<n2:Formula/>
</n1:disapproves>
<n2:wants>
<n2:Physical/>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction/>
</n1:plaintiff>
<n2:knows>
<n2:Formula/>
</n2:knows>
<n2:desires>
<n2:Formula/>
</n2:desires>
<n1:student>
<n2:EducationalOrganization/>
</n1:student>
<n2:considers>
<n2:Formula/>
</n2:considers>
<n1:doubts>
<n2:Formula/>
</n1:doubts>
</n2:Organization>
</n1:ExecutiveBranchFn>
<n1:customer>
<n2:Corporation>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
</n2:Corporation>
</n1:customer>
<n1:governmentType>
<n1:FormOfGovernment/>
</n1:governmentType>
<n1:leaderPosition>
<n2:Position/>
</n1:leaderPosition>
<n1:fiscalYearPeriod>
<n2:TimeInterval>
<n2:starts>
<n2:TimeInterval/>
</n2:starts>
<n2:finishes>
<n2:TimeInterval/>
</n2:finishes>
<n2:BeginFn>
<n2:TimePoint/>
</n2:BeginFn>
<n2:duration>
<n2:TimeDuration/>
</n2:duration>
<n2:during>
<n2:TimeInterval/>
</n2:during>
<n2:EndFn>
<n2:TimePoint/>
</n2:EndFn>
<n2:earlier>
<n2:TimeInterval/>
</n2:earlier>
<n2:meetsTemporally>
<n2:TimeInterval/>
</n2:meetsTemporally>
<n2:FutureFn>
<n2:TimeInterval/>
</n2:FutureFn>
<n2:ImmediatePastFn>
<n2:TimeInterval/>
</n2:ImmediatePastFn>
<n2:PastFn>
<n2:TimeInterval/>
</n2:PastFn>
<n2:ImmediateFutureFn>
<n2:TimeInterval/>
</n2:ImmediateFutureFn>
<n2:holdsDuring>
<n2:Formula/>
</n2:holdsDuring>
</n2:TimeInterval>
</n1:fiscalYearPeriod>
</n2:GeopoliticalArea>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization>
<n1:yearOfFounding>
<n2:Integer>
<n2:SuccessorFn>
<n2:Integer/>
</n2:SuccessorFn>
<n2:PredecessorFn>
<n2:Integer/>
</n2:PredecessorFn>
<n1:multiplicativeFactor>
<n2:Integer/>
</n1:multiplicativeFactor>
</n2:Integer>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea>
<n1:JudiciaryFn>
<n2:JudicialOrganization/>
</n1:JudiciaryFn>
<n1:dependentGeopoliticalArea>
<n2:GeopoliticalArea/>
</n1:dependentGeopoliticalArea>
<n1:totalGDP>
<n2:CurrencyMeasure/>
</n1:totalGDP>
<n1:CitizenryFn>
<n2:GroupOfPeople/>
</n1:CitizenryFn>
<n2:GovernmentFn>
<n2:Government/>
</n2:GovernmentFn>
<n1:currencyType>
<n2:CurrencyMeasure/>
</n1:currencyType>
<n1:legalSystemType>
<n1:LegalSystemAttribute/>
</n1:legalSystemType>
<n1:primaryGeopoliticalSubdivision>
<n2:GeopoliticalArea/>
</n1:primaryGeopoliticalSubdivision>
<n1:LegislatureFn>
<n1:LegislativeOrganization/>
</n1:LegislatureFn>
<n1:industryOfArea>
<n2:Physical/>
</n1:industryOfArea>
<n1:climateTypeInArea>
<n1:ClimateZone/>
</n1:climateTypeInArea>
<n1:financialAsset>
<n2:Object/>
</n1:financialAsset>
<n2:leader>
<n2:Human/>
</n2:leader>
<n1:economyType>
<n1:EconomicAttribute/>
</n1:economyType>
<n2:editor>
<n2:Text/>
</n2:editor>
<n2:authors>
<n2:Text/>
</n2:authors>
<n2:WealthFn>
<n2:CurrencyMeasure/>
</n2:WealthFn>
<n2:PropertyFn>
<n2:Set/>
</n2:PropertyFn>
<n1:ExecutiveBranchFn>
<n2:Organization/>
</n1:ExecutiveBranchFn>
<n1:customer>
<n2:Corporation/>
</n1:customer>
<n1:governmentType>
<n1:FormOfGovernment/>
</n1:governmentType>
<n1:leaderPosition>
<n2:Position/>
</n1:leaderPosition>
<n1:fiscalYearPeriod>
<n2:TimeInterval/>
</n1:fiscalYearPeriod>
</n2:GeopoliticalArea>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
<n1:teacher>
<n2:EducationalOrganization/>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy/>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent/>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object/>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess/>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction/>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent/>
</n1:allegiance>
<n1:disapproves>
<n2:Formula/>
</n1:disapproves>
<n2:wants>
<n2:Physical/>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction/>
</n1:plaintiff>
<n2:knows>
<n2:Formula/>
</n2:knows>
<n2:desires>
<n2:Formula/>
</n2:desires>
<n1:student>
<n2:EducationalOrganization/>
</n1:student>
<n2:considers>
<n2:Formula/>
</n2:considers>
<n1:doubts>
<n2:Formula/>
</n1:doubts>
</n2:Organization>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea>
<n1:JudiciaryFn>
<n2:JudicialOrganization/>
</n1:JudiciaryFn>
<n1:dependentGeopoliticalArea>
<n2:GeopoliticalArea/>
</n1:dependentGeopoliticalArea>
<n1:totalGDP>
<n2:CurrencyMeasure/>
</n1:totalGDP>
<n1:CitizenryFn>
<n2:GroupOfPeople/>
</n1:CitizenryFn>
<n2:GovernmentFn>
<n2:Government/>
</n2:GovernmentFn>
<n1:currencyType>
<n2:CurrencyMeasure/>
</n1:currencyType>
<n1:legalSystemType>
<n1:LegalSystemAttribute/>
</n1:legalSystemType>
<n1:primaryGeopoliticalSubdivision>
<n2:GeopoliticalArea/>
</n1:primaryGeopoliticalSubdivision>
<n1:LegislatureFn>
<n1:LegislativeOrganization/>
</n1:LegislatureFn>
<n1:industryOfArea>
<n2:Physical/>
</n1:industryOfArea>
<n1:climateTypeInArea>
<n1:ClimateZone/>
</n1:climateTypeInArea>
<n1:financialAsset>
<n2:Object/>
</n1:financialAsset>
<n2:leader>
<n2:Human/>
</n2:leader>
<n1:economyType>
<n1:EconomicAttribute/>
</n1:economyType>
<n2:editor>
<n2:Text/>
</n2:editor>
<n2:authors>
<n2:Text/>
</n2:authors>
<n2:WealthFn>
<n2:CurrencyMeasure/>
</n2:WealthFn>
<n2:PropertyFn>
<n2:Set/>
</n2:PropertyFn>
<n1:ExecutiveBranchFn>
<n2:Organization/>
</n1:ExecutiveBranchFn>
<n1:customer>
<n2:Corporation/>
</n1:customer>
<n1:governmentType>
<n1:FormOfGovernment/>
</n1:governmentType>
<n1:leaderPosition>
<n2:Position/>
</n1:leaderPosition>
<n1:fiscalYearPeriod>
<n2:TimeInterval/>
</n1:fiscalYearPeriod>
</n2:GeopoliticalArea>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text>
<n1:registeredItem>
<n2:Physical/>
</n1:registeredItem>
<n2:version>
<n2:Artifact/>
</n2:version>
<n1:equipmentType>
<n2:Device/>
</n1:equipmentType>
<n2:expressedInLanguage>
<n2:Language/>
</n2:expressedInLanguage>
</n2:Text>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent>
<n1:teacher>
<n2:EducationalOrganization/>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy/>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent/>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object/>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess/>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction/>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent/>
</n1:allegiance>
<n1:disapproves>
<n2:Formula/>
</n1:disapproves>
<n2:wants>
<n2:Physical/>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction/>
</n1:plaintiff>
<n2:knows>
<n2:Formula/>
</n2:knows>
<n2:desires>
<n2:Formula/>
</n2:desires>
<n1:student>
<n2:EducationalOrganization/>
</n1:student>
<n2:considers>
<n2:Formula/>
</n2:considers>
<n1:doubts>
<n2:Formula/>
</n1:doubts>
<n1:speaksLanguage>
<n2:Language/>
</n1:speaksLanguage>
</n2:CognitiveAgent>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
<n1:teacher>
<n2:EducationalOrganization/>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy/>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent/>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object/>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess/>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction/>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent/>
</n1:allegiance>
<n1:disapproves>
<n2:Formula/>
</n1:disapproves>
<n2:wants>
<n2:Physical/>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction/>
</n1:plaintiff>
<n2:knows>
<n2:Formula/>
</n2:knows>
<n2:desires>
<n2:Formula/>
</n2:desires>
<n1:student>
<n2:EducationalOrganization/>
</n1:student>
<n2:considers>
<n2:Formula/>
</n2:considers>
<n1:doubts>
<n2:Formula/>
</n1:doubts>
</n2:Organization>
</n1:ancestorOrganization>
<n1:teacher>
<n2:EducationalOrganization>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
</n2:EducationalOrganization>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy>
<n1:subField>
<n2:FieldOfStudy/>
</n1:subField>
<n2:consistent>
<n2:Proposition/>
</n2:consistent>
</n2:FieldOfStudy>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent>
<n1:teacher>
<n2:EducationalOrganization/>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy/>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent/>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object/>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess/>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction/>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent/>
</n1:allegiance>
<n1:disapproves>
<n2:Formula/>
</n1:disapproves>
<n2:wants>
<n2:Physical/>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction/>
</n1:plaintiff>
<n2:knows>
<n2:Formula/>
</n2:knows>
<n2:desires>
<n2:Formula/>
</n2:desires>
<n1:student>
<n2:EducationalOrganization/>
</n1:student>
<n2:considers>
<n2:Formula/>
</n2:considers>
<n1:doubts>
<n2:Formula/>
</n1:doubts>
<n1:speaksLanguage>
<n2:Language/>
</n1:speaksLanguage>
</n2:CognitiveAgent>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object>
<n2:larger>
<n2:Object/>
</n2:larger>
<n1:deviceState>
<n1:DeviceStateAttribute/>
</n1:deviceState>
<n2:faces>
<n2:DirectionalAttribute/>
</n2:faces>
<n1:older>
<n2:Object/>
</n1:older>
<n2:copy>
<n2:Object/>
</n2:copy>
<n2:uses>
<n2:Agent/>
</n2:uses>
<n2:linked>
<n2:Object/>
</n2:linked>
<n2:exploits>
<n2:Agent/>
</n2:exploits>
<n2:fills>
<n2:Hole/>
</n2:fills>
<n1:orbits>
<n2:AstronomicalBody/>
</n1:orbits>
<n1:barometricPressure>
<n1:AtmosphericPressureMeasure/>
</n1:barometricPressure>
<n2:smaller>
<n2:Object/>
</n2:smaller>
<n1:airTemperature>
<n2:TemperatureMeasure/>
</n1:airTemperature>
<n2:hasPurpose>
<n2:Formula/>
</n2:hasPurpose>
<n2:date>
<n2:Day/>
</n2:date>
<n2:WhenFn>
<n2:TimeInterval/>
</n2:WhenFn>
<n2:cooccur>
<n2:Physical/>
</n2:cooccur>
<n2:monetaryValue>
<n2:CurrencyMeasure/>
</n2:monetaryValue>
</n2:Object>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess>
<n2:subProcess>
<n2:Process/>
</n2:subProcess>
<n2:frequency>
<n2:TimeDuration/>
</n2:frequency>
<n2:realization>
<n2:Proposition/>
</n2:realization>
<n2:result>
<n2:Entity/>
</n2:result>
<n2:causesSubclass>
<n2:Process/>
</n2:causesSubclass>
<n2:inhibits>
<n2:Process/>
</n2:inhibits>
<n2:hasSkill>
<n2:Agent/>
</n2:hasSkill>
<n2:precondition>
<n2:Process/>
</n2:precondition>
<n2:causes>
<n2:Process/>
</n2:causes>
<n2:direction>
<n2:DirectionalAttribute/>
</n2:direction>
<n2:destination>
<n2:Entity/>
</n2:destination>
<n2:origin>
<n2:Object/>
</n2:origin>
<n1:targetInAttack>
<n2:Object/>
</n1:targetInAttack>
<n2:prevents>
<n2:Process/>
</n2:prevents>
</n2:IntentionalProcess>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction>
<n1:contestParticipant>
<n2:Agent/>
</n1:contestParticipant>
</n2:LegalAction>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent>
<n1:teacher>
<n2:EducationalOrganization/>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy/>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent/>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object/>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess/>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction/>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent/>
</n1:allegiance>
<n1:disapproves>
<n2:Formula/>
</n1:disapproves>
<n2:wants>
<n2:Physical/>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction/>
</n1:plaintiff>
<n2:knows>
<n2:Formula/>
</n2:knows>
<n2:desires>
<n2:Formula/>
</n2:desires>
<n1:student>
<n2:EducationalOrganization/>
</n1:student>
<n2:considers>
<n2:Formula/>
</n2:considers>
<n1:doubts>
<n2:Formula/>
</n1:doubts>
<n1:speaksLanguage>
<n2:Language/>
</n1:speaksLanguage>
</n2:CognitiveAgent>
</n1:allegiance>
<n1:disapproves>
<n2:Formula>
<n2:ProbabilityFn>
<n2:RealNumber/>
</n2:ProbabilityFn>
<n2:decreasesLikelihood>
<n2:Formula/>
</n2:decreasesLikelihood>
<n2:independentProbability>
<n2:Formula/>
</n2:independentProbability>
<n2:increasesLikelihood>
<n2:Formula/>
</n2:increasesLikelihood>
<n2:modalAttribute>
<n2:NormativeAttribute/>
</n2:modalAttribute>
<n2:entails>
<n2:Formula/>
</n2:entails>
<n2:true>
<n2:TruthValue/>
</n2:true>
</n2:Formula>
</n1:disapproves>
<n2:wants>
<n2:Physical>
<n2:hasPurpose>
<n2:Formula/>
</n2:hasPurpose>
<n2:date>
<n2:Day/>
</n2:date>
<n2:WhenFn>
<n2:TimeInterval/>
</n2:WhenFn>
<n2:cooccur>
<n2:Physical/>
</n2:cooccur>
<n2:monetaryValue>
<n2:CurrencyMeasure/>
</n2:monetaryValue>
</n2:Physical>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction>
<n1:contestParticipant>
<n2:Agent/>
</n1:contestParticipant>
</n2:LegalAction>
</n1:plaintiff>
<n2:knows>
<n2:Formula>
<n2:ProbabilityFn>
<n2:RealNumber/>
</n2:ProbabilityFn>
<n2:decreasesLikelihood>
<n2:Formula/>
</n2:decreasesLikelihood>
<n2:independentProbability>
<n2:Formula/>
</n2:independentProbability>
<n2:increasesLikelihood>
<n2:Formula/>
</n2:increasesLikelihood>
<n2:modalAttribute>
<n2:NormativeAttribute/>
</n2:modalAttribute>
<n2:entails>
<n2:Formula/>
</n2:entails>
<n2:true>
<n2:TruthValue/>
</n2:true>
</n2:Formula>
</n2:knows>
<n2:desires>
<n2:Formula>
<n2:ProbabilityFn>
<n2:RealNumber/>
</n2:ProbabilityFn>
<n2:decreasesLikelihood>
<n2:Formula/>
</n2:decreasesLikelihood>
<n2:independentProbability>
<n2:Formula/>
</n2:independentProbability>
<n2:increasesLikelihood>
<n2:Formula/>
</n2:increasesLikelihood>
<n2:modalAttribute>
<n2:NormativeAttribute/>
</n2:modalAttribute>
<n2:entails>
<n2:Formula/>
</n2:entails>
<n2:true>
<n2:TruthValue/>
</n2:true>
</n2:Formula>
</n2:desires>
<n1:student>
<n2:EducationalOrganization>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
</n2:EducationalOrganization>
</n1:student>
<n2:considers>
<n2:Formula>
<n2:ProbabilityFn>
<n2:RealNumber/>
</n2:ProbabilityFn>
<n2:decreasesLikelihood>
<n2:Formula/>
</n2:decreasesLikelihood>
<n2:independentProbability>
<n2:Formula/>
</n2:independentProbability>
<n2:increasesLikelihood>
<n2:Formula/>
</n2:increasesLikelihood>
<n2:modalAttribute>
<n2:NormativeAttribute/>
</n2:modalAttribute>
<n2:entails>
<n2:Formula/>
</n2:entails>
<n2:true>
<n2:TruthValue/>
</n2:true>
</n2:Formula>
</n2:considers>
<n1:doubts>
<n2:Formula>
<n2:ProbabilityFn>
<n2:RealNumber/>
</n2:ProbabilityFn>
<n2:decreasesLikelihood>
<n2:Formula/>
</n2:decreasesLikelihood>
<n2:independentProbability>
<n2:Formula/>
</n2:independentProbability>
<n2:increasesLikelihood>
<n2:Formula/>
</n2:increasesLikelihood>
<n2:modalAttribute>
<n2:NormativeAttribute/>
</n2:modalAttribute>
<n2:entails>
<n2:Formula/>
</n2:entails>
<n2:true>
<n2:TruthValue/>
</n2:true>
</n2:Formula>
</n1:doubts>
</n2:Organization>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea>
<n1:JudiciaryFn>
<n2:JudicialOrganization>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
</n2:JudicialOrganization>
</n1:JudiciaryFn>
<n1:dependentGeopoliticalArea>
<n2:GeopoliticalArea>
<n1:JudiciaryFn>
<n2:JudicialOrganization/>
</n1:JudiciaryFn>
<n1:dependentGeopoliticalArea>
<n2:GeopoliticalArea/>
</n1:dependentGeopoliticalArea>
<n1:totalGDP>
<n2:CurrencyMeasure/>
</n1:totalGDP>
<n1:CitizenryFn>
<n2:GroupOfPeople/>
</n1:CitizenryFn>
<n2:GovernmentFn>
<n2:Government/>
</n2:GovernmentFn>
<n1:currencyType>
<n2:CurrencyMeasure/>
</n1:currencyType>
<n1:legalSystemType>
<n1:LegalSystemAttribute/>
</n1:legalSystemType>
<n1:primaryGeopoliticalSubdivision>
<n2:GeopoliticalArea/>
</n1:primaryGeopoliticalSubdivision>
<n1:LegislatureFn>
<n1:LegislativeOrganization/>
</n1:LegislatureFn>
<n1:industryOfArea>
<n2:Physical/>
</n1:industryOfArea>
<n1:climateTypeInArea>
<n1:ClimateZone/>
</n1:climateTypeInArea>
<n1:financialAsset>
<n2:Object/>
</n1:financialAsset>
<n2:leader>
<n2:Human/>
</n2:leader>
<n1:economyType>
<n1:EconomicAttribute/>
</n1:economyType>
<n2:editor>
<n2:Text/>
</n2:editor>
<n2:authors>
<n2:Text/>
</n2:authors>
<n2:WealthFn>
<n2:CurrencyMeasure/>
</n2:WealthFn>
<n2:PropertyFn>
<n2:Set/>
</n2:PropertyFn>
<n1:ExecutiveBranchFn>
<n2:Organization/>
</n1:ExecutiveBranchFn>
<n1:customer>
<n2:Corporation/>
</n1:customer>
<n1:governmentType>
<n1:FormOfGovernment/>
</n1:governmentType>
<n1:leaderPosition>
<n2:Position/>
</n1:leaderPosition>
<n1:fiscalYearPeriod>
<n2:TimeInterval/>
</n1:fiscalYearPeriod>
</n2:GeopoliticalArea>
</n1:dependentGeopoliticalArea>
<n1:totalGDP>
<n2:CurrencyMeasure>
<n2:MagnitudeFn>
<n2:RealNumber/>
</n2:MagnitudeFn>
</n2:CurrencyMeasure>
</n1:totalGDP>
<n1:CitizenryFn>
<n2:GroupOfPeople/>
</n1:CitizenryFn>
<n2:GovernmentFn>
<n2:Government/>
</n2:GovernmentFn>
<n1:currencyType>
<n2:CurrencyMeasure>
<n2:MagnitudeFn>
<n2:RealNumber/>
</n2:MagnitudeFn>
</n2:CurrencyMeasure>
</n1:currencyType>
<n1:legalSystemType>
<n1:LegalSystemAttribute/>
</n1:legalSystemType>
<n1:primaryGeopoliticalSubdivision>
<n2:GeopoliticalArea>
<n1:JudiciaryFn>
<n2:JudicialOrganization/>
</n1:JudiciaryFn>
<n1:dependentGeopoliticalArea>
<n2:GeopoliticalArea/>
</n1:dependentGeopoliticalArea>
<n1:totalGDP>
<n2:CurrencyMeasure/>
</n1:totalGDP>
<n1:CitizenryFn>
<n2:GroupOfPeople/>
</n1:CitizenryFn>
<n2:GovernmentFn>
<n2:Government/>
</n2:GovernmentFn>
<n1:currencyType>
<n2:CurrencyMeasure/>
</n1:currencyType>
<n1:legalSystemType>
<n1:LegalSystemAttribute/>
</n1:legalSystemType>
<n1:primaryGeopoliticalSubdivision>
<n2:GeopoliticalArea/>
</n1:primaryGeopoliticalSubdivision>
<n1:LegislatureFn>
<n1:LegislativeOrganization/>
</n1:LegislatureFn>
<n1:industryOfArea>
<n2:Physical/>
</n1:industryOfArea>
<n1:climateTypeInArea>
<n1:ClimateZone/>
</n1:climateTypeInArea>
<n1:financialAsset>
<n2:Object/>
</n1:financialAsset>
<n2:leader>
<n2:Human/>
</n2:leader>
<n1:economyType>
<n1:EconomicAttribute/>
</n1:economyType>
<n2:editor>
<n2:Text/>
</n2:editor>
<n2:authors>
<n2:Text/>
</n2:authors>
<n2:WealthFn>
<n2:CurrencyMeasure/>
</n2:WealthFn>
<n2:PropertyFn>
<n2:Set/>
</n2:PropertyFn>
<n1:ExecutiveBranchFn>
<n2:Organization/>
</n1:ExecutiveBranchFn>
<n1:customer>
<n2:Corporation/>
</n1:customer>
<n1:governmentType>
<n1:FormOfGovernment/>
</n1:governmentType>
<n1:leaderPosition>
<n2:Position/>
</n1:leaderPosition>
<n1:fiscalYearPeriod>
<n2:TimeInterval/>
</n1:fiscalYearPeriod>
</n2:GeopoliticalArea>
</n1:primaryGeopoliticalSubdivision>
<n1:LegislatureFn>
<n1:LegislativeOrganization>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
</n1:LegislativeOrganization>
</n1:LegislatureFn>
<n1:industryOfArea>
<n2:Physical>
<n2:hasPurpose>
<n2:Formula/>
</n2:hasPurpose>
<n2:date>
<n2:Day/>
</n2:date>
<n2:WhenFn>
<n2:TimeInterval/>
</n2:WhenFn>
<n2:cooccur>
<n2:Physical/>
</n2:cooccur>
<n2:monetaryValue>
<n2:CurrencyMeasure/>
</n2:monetaryValue>
</n2:Physical>
</n1:industryOfArea>
<n1:climateTypeInArea>
<n1:ClimateZone>
<n1:climateTypeInArea>
<n1:ClimateZone/>
</n1:climateTypeInArea>
</n1:ClimateZone>
</n1:climateTypeInArea>
<n1:financialAsset>
<n2:Object>
<n2:larger>
<n2:Object/>
</n2:larger>
<n1:deviceState>
<n1:DeviceStateAttribute/>
</n1:deviceState>
<n2:faces>
<n2:DirectionalAttribute/>
</n2:faces>
<n1:older>
<n2:Object/>
</n1:older>
<n2:copy>
<n2:Object/>
</n2:copy>
<n2:uses>
<n2:Agent/>
</n2:uses>
<n2:linked>
<n2:Object/>
</n2:linked>
<n2:exploits>
<n2:Agent/>
</n2:exploits>
<n2:fills>
<n2:Hole/>
</n2:fills>
<n1:orbits>
<n2:AstronomicalBody/>
</n1:orbits>
<n1:barometricPressure>
<n1:AtmosphericPressureMeasure/>
</n1:barometricPressure>
<n2:smaller>
<n2:Object/>
</n2:smaller>
<n1:airTemperature>
<n2:TemperatureMeasure/>
</n1:airTemperature>
<n2:hasPurpose>
<n2:Formula/>
</n2:hasPurpose>
<n2:date>
<n2:Day/>
</n2:date>
<n2:WhenFn>
<n2:TimeInterval/>
</n2:WhenFn>
<n2:cooccur>
<n2:Physical/>
</n2:cooccur>
<n2:monetaryValue>
<n2:CurrencyMeasure/>
</n2:monetaryValue>
</n2:Object>
</n1:financialAsset>
<n2:leader>
<n2:Human>
<n1:intelligenceQuotient>
<n2:RationalNumber/>
</n1:intelligenceQuotient>
<n1:grandfather>
<n2:Man/>
</n1:grandfather>
<n2:citizen>
<n2:Nation/>
</n2:citizen>
<n2:ImmediateFamilyFn>
<n2:FamilyGroup/>
</n2:ImmediateFamilyFn>
<n1:birthday>
<n2:Day/>
</n1:birthday>
<n2:home>
<n2:PermanentResidence/>
</n2:home>
<n1:stepmother>
<n2:Woman/>
</n1:stepmother>
<n1:tenant>
<n2:Residence/>
</n1:tenant>
<n1:occupation>
<n2:FinancialTransaction/>
</n1:occupation>
<n1:groupMember>
<n2:GroupOfPeople/>
</n1:groupMember>
<n1:neighbor>
<n2:Human/>
</n1:neighbor>
<n1:DescendantsFn>
<n2:FamilyGroup/>
</n1:DescendantsFn>
<n1:grandmother>
<n2:Man/>
</n1:grandmother>
<n1:stepfather>
<n2:Man/>
</n1:stepfather>
<n1:cousin>
<n2:Human/>
</n1:cousin>
<n2:stays>
<n2:TemporaryResidence/>
</n2:stays>
<n1:patientMedical>
<n2:CognitiveAgent/>
</n1:patientMedical>
<n1:teacher>
<n2:EducationalOrganization/>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy/>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent/>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object/>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess/>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction/>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent/>
</n1:allegiance>
<n1:disapproves>
<n2:Formula/>
</n1:disapproves>
<n2:wants>
<n2:Physical/>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction/>
</n1:plaintiff>
<n2:knows>
<n2:Formula/>
</n2:knows>
<n2:desires>
<n2:Formula/>
</n2:desires>
<n1:student>
<n2:EducationalOrganization/>
</n1:student>
<n2:considers>
<n2:Formula/>
</n2:considers>
<n1:doubts>
<n2:Formula/>
</n1:doubts>
</n2:Human>
</n2:leader>
<n1:economyType>
<n1:EconomicAttribute/>
</n1:economyType>
<n2:editor>
<n2:Text>
<n1:registeredItem>
<n2:Physical/>
</n1:registeredItem>
<n2:version>
<n2:Artifact/>
</n2:version>
<n1:equipmentType>
<n2:Device/>
</n1:equipmentType>
<n2:expressedInLanguage>
<n2:Language/>
</n2:expressedInLanguage>
</n2:Text>
</n2:editor>
<n2:authors>
<n2:Text>
<n1:registeredItem>
<n2:Physical/>
</n1:registeredItem>
<n2:version>
<n2:Artifact/>
</n2:version>
<n1:equipmentType>
<n2:Device/>
</n1:equipmentType>
<n2:expressedInLanguage>
<n2:Language/>
</n2:expressedInLanguage>
</n2:Text>
</n2:authors>
<n2:WealthFn>
<n2:CurrencyMeasure>
<n2:MagnitudeFn>
<n2:RealNumber/>
</n2:MagnitudeFn>
</n2:CurrencyMeasure>
</n2:WealthFn>
<n2:PropertyFn>
<n2:Set>
<n2:subset>
<n2:Set/>
</n2:subset>
<n2:ComplementFn>
<n2:SetOrClass/>
</n2:ComplementFn>
<n2:GeneralizedIntersectionFn>
<n2:SetOrClass/>
</n2:GeneralizedIntersectionFn>
<n2:GeneralizedUnionFn>
<n2:SetOrClass/>
</n2:GeneralizedUnionFn>
<n2:disjoint>
<n2:SetOrClass/>
</n2:disjoint>
</n2:Set>
</n2:PropertyFn>
<n1:ExecutiveBranchFn>
<n2:Organization>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
<n1:teacher>
<n2:EducationalOrganization/>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy/>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent/>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object/>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess/>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction/>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent/>
</n1:allegiance>
<n1:disapproves>
<n2:Formula/>
</n1:disapproves>
<n2:wants>
<n2:Physical/>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction/>
</n1:plaintiff>
<n2:knows>
<n2:Formula/>
</n2:knows>
<n2:desires>
<n2:Formula/>
</n2:desires>
<n1:student>
<n2:EducationalOrganization/>
</n1:student>
<n2:considers>
<n2:Formula/>
</n2:considers>
<n1:doubts>
<n2:Formula/>
</n1:doubts>
</n2:Organization>
</n1:ExecutiveBranchFn>
<n1:customer>
<n2:Corporation>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
</n2:Corporation>
</n1:customer>
<n1:governmentType>
<n1:FormOfGovernment/>
</n1:governmentType>
<n1:leaderPosition>
<n2:Position/>
</n1:leaderPosition>
<n1:fiscalYearPeriod>
<n2:TimeInterval>
<n2:starts>
<n2:TimeInterval/>
</n2:starts>
<n2:finishes>
<n2:TimeInterval/>
</n2:finishes>
<n2:BeginFn>
<n2:TimePoint/>
</n2:BeginFn>
<n2:duration>
<n2:TimeDuration/>
</n2:duration>
<n2:during>
<n2:TimeInterval/>
</n2:during>
<n2:EndFn>
<n2:TimePoint/>
</n2:EndFn>
<n2:earlier>
<n2:TimeInterval/>
</n2:earlier>
<n2:meetsTemporally>
<n2:TimeInterval/>
</n2:meetsTemporally>
<n2:FutureFn>
<n2:TimeInterval/>
</n2:FutureFn>
<n2:ImmediatePastFn>
<n2:TimeInterval/>
</n2:ImmediatePastFn>
<n2:PastFn>
<n2:TimeInterval/>
</n2:PastFn>
<n2:ImmediateFutureFn>
<n2:TimeInterval/>
</n2:ImmediateFutureFn>
<n2:holdsDuring>
<n2:Formula/>
</n2:holdsDuring>
</n2:TimeInterval>
</n1:fiscalYearPeriod>
</n2:GeopoliticalArea>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text>
<n1:registeredItem>
<n2:Physical>
<n2:hasPurpose>
<n2:Formula/>
</n2:hasPurpose>
<n2:date>
<n2:Day/>
</n2:date>
<n2:WhenFn>
<n2:TimeInterval/>
</n2:WhenFn>
<n2:cooccur>
<n2:Physical/>
</n2:cooccur>
<n2:monetaryValue>
<n2:CurrencyMeasure/>
</n2:monetaryValue>
</n2:Physical>
</n1:registeredItem>
<n2:version>
<n2:Artifact>
<n2:version>
<n2:Artifact/>
</n2:version>
<n1:equipmentType>
<n2:Device/>
</n1:equipmentType>
</n2:Artifact>
</n2:version>
<n1:equipmentType>
<n2:Device>
<n1:powerPlant>
<n2:Artifact/>
</n1:powerPlant>
<n2:version>
<n2:Artifact/>
</n2:version>
<n1:equipmentType>
<n2:Device/>
</n1:equipmentType>
</n2:Device>
</n1:equipmentType>
<n2:expressedInLanguage>
<n2:Language>
<n2:expressedInLanguage>
<n2:Language/>
</n2:expressedInLanguage>
</n2:Language>
</n2:expressedInLanguage>
</n2:Text>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent>
<n1:teacher>
<n2:EducationalOrganization>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
</n2:EducationalOrganization>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy>
<n1:subField>
<n2:FieldOfStudy/>
</n1:subField>
<n2:consistent>
<n2:Proposition/>
</n2:consistent>
</n2:FieldOfStudy>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent>
<n1:teacher>
<n2:EducationalOrganization/>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy/>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent/>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object/>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess/>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction/>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent/>
</n1:allegiance>
<n1:disapproves>
<n2:Formula/>
</n1:disapproves>
<n2:wants>
<n2:Physical/>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction/>
</n1:plaintiff>
<n2:knows>
<n2:Formula/>
</n2:knows>
<n2:desires>
<n2:Formula/>
</n2:desires>
<n1:student>
<n2:EducationalOrganization/>
</n1:student>
<n2:considers>
<n2:Formula/>
</n2:considers>
<n1:doubts>
<n2:Formula/>
</n1:doubts>
<n1:speaksLanguage>
<n2:Language/>
</n1:speaksLanguage>
</n2:CognitiveAgent>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object>
<n2:larger>
<n2:Object/>
</n2:larger>
<n1:deviceState>
<n1:DeviceStateAttribute/>
</n1:deviceState>
<n2:faces>
<n2:DirectionalAttribute/>
</n2:faces>
<n1:older>
<n2:Object/>
</n1:older>
<n2:copy>
<n2:Object/>
</n2:copy>
<n2:uses>
<n2:Agent/>
</n2:uses>
<n2:linked>
<n2:Object/>
</n2:linked>
<n2:exploits>
<n2:Agent/>
</n2:exploits>
<n2:fills>
<n2:Hole/>
</n2:fills>
<n1:orbits>
<n2:AstronomicalBody/>
</n1:orbits>
<n1:barometricPressure>
<n1:AtmosphericPressureMeasure/>
</n1:barometricPressure>
<n2:smaller>
<n2:Object/>
</n2:smaller>
<n1:airTemperature>
<n2:TemperatureMeasure/>
</n1:airTemperature>
<n2:hasPurpose>
<n2:Formula/>
</n2:hasPurpose>
<n2:date>
<n2:Day/>
</n2:date>
<n2:WhenFn>
<n2:TimeInterval/>
</n2:WhenFn>
<n2:cooccur>
<n2:Physical/>
</n2:cooccur>
<n2:monetaryValue>
<n2:CurrencyMeasure/>
</n2:monetaryValue>
</n2:Object>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess>
<n2:subProcess>
<n2:Process/>
</n2:subProcess>
<n2:frequency>
<n2:TimeDuration/>
</n2:frequency>
<n2:realization>
<n2:Proposition/>
</n2:realization>
<n2:result>
<n2:Entity/>
</n2:result>
<n2:causesSubclass>
<n2:Process/>
</n2:causesSubclass>
<n2:inhibits>
<n2:Process/>
</n2:inhibits>
<n2:hasSkill>
<n2:Agent/>
</n2:hasSkill>
<n2:precondition>
<n2:Process/>
</n2:precondition>
<n2:causes>
<n2:Process/>
</n2:causes>
<n2:direction>
<n2:DirectionalAttribute/>
</n2:direction>
<n2:destination>
<n2:Entity/>
</n2:destination>
<n2:origin>
<n2:Object/>
</n2:origin>
<n1:targetInAttack>
<n2:Object/>
</n1:targetInAttack>
<n2:prevents>
<n2:Process/>
</n2:prevents>
</n2:IntentionalProcess>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction>
<n1:contestParticipant>
<n2:Agent/>
</n1:contestParticipant>
</n2:LegalAction>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent>
<n1:teacher>
<n2:EducationalOrganization/>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy/>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent/>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object/>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess/>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction/>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent/>
</n1:allegiance>
<n1:disapproves>
<n2:Formula/>
</n1:disapproves>
<n2:wants>
<n2:Physical/>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction/>
</n1:plaintiff>
<n2:knows>
<n2:Formula/>
</n2:knows>
<n2:desires>
<n2:Formula/>
</n2:desires>
<n1:student>
<n2:EducationalOrganization/>
</n1:student>
<n2:considers>
<n2:Formula/>
</n2:considers>
<n1:doubts>
<n2:Formula/>
</n1:doubts>
<n1:speaksLanguage>
<n2:Language/>
</n1:speaksLanguage>
</n2:CognitiveAgent>
</n1:allegiance>
<n1:disapproves>
<n2:Formula>
<n2:ProbabilityFn>
<n2:RealNumber/>
</n2:ProbabilityFn>
<n2:decreasesLikelihood>
<n2:Formula/>
</n2:decreasesLikelihood>
<n2:independentProbability>
<n2:Formula/>
</n2:independentProbability>
<n2:increasesLikelihood>
<n2:Formula/>
</n2:increasesLikelihood>
<n2:modalAttribute>
<n2:NormativeAttribute/>
</n2:modalAttribute>
<n2:entails>
<n2:Formula/>
</n2:entails>
<n2:true>
<n2:TruthValue/>
</n2:true>
</n2:Formula>
</n1:disapproves>
<n2:wants>
<n2:Physical>
<n2:hasPurpose>
<n2:Formula/>
</n2:hasPurpose>
<n2:date>
<n2:Day/>
</n2:date>
<n2:WhenFn>
<n2:TimeInterval/>
</n2:WhenFn>
<n2:cooccur>
<n2:Physical/>
</n2:cooccur>
<n2:monetaryValue>
<n2:CurrencyMeasure/>
</n2:monetaryValue>
</n2:Physical>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction>
<n1:contestParticipant>
<n2:Agent/>
</n1:contestParticipant>
</n2:LegalAction>
</n1:plaintiff>
<n2:knows>
<n2:Formula>
<n2:ProbabilityFn>
<n2:RealNumber/>
</n2:ProbabilityFn>
<n2:decreasesLikelihood>
<n2:Formula/>
</n2:decreasesLikelihood>
<n2:independentProbability>
<n2:Formula/>
</n2:independentProbability>
<n2:increasesLikelihood>
<n2:Formula/>
</n2:increasesLikelihood>
<n2:modalAttribute>
<n2:NormativeAttribute/>
</n2:modalAttribute>
<n2:entails>
<n2:Formula/>
</n2:entails>
<n2:true>
<n2:TruthValue/>
</n2:true>
</n2:Formula>
</n2:knows>
<n2:desires>
<n2:Formula>
<n2:ProbabilityFn>
<n2:RealNumber/>
</n2:ProbabilityFn>
<n2:decreasesLikelihood>
<n2:Formula/>
</n2:decreasesLikelihood>
<n2:independentProbability>
<n2:Formula/>
</n2:independentProbability>
<n2:increasesLikelihood>
<n2:Formula/>
</n2:increasesLikelihood>
<n2:modalAttribute>
<n2:NormativeAttribute/>
</n2:modalAttribute>
<n2:entails>
<n2:Formula/>
</n2:entails>
<n2:true>
<n2:TruthValue/>
</n2:true>
</n2:Formula>
</n2:desires>
<n1:student>
<n2:EducationalOrganization>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
</n2:EducationalOrganization>
</n1:student>
<n2:considers>
<n2:Formula>
<n2:ProbabilityFn>
<n2:RealNumber/>
</n2:ProbabilityFn>
<n2:decreasesLikelihood>
<n2:Formula/>
</n2:decreasesLikelihood>
<n2:independentProbability>
<n2:Formula/>
</n2:independentProbability>
<n2:increasesLikelihood>
<n2:Formula/>
</n2:increasesLikelihood>
<n2:modalAttribute>
<n2:NormativeAttribute/>
</n2:modalAttribute>
<n2:entails>
<n2:Formula/>
</n2:entails>
<n2:true>
<n2:TruthValue/>
</n2:true>
</n2:Formula>
</n2:considers>
<n1:doubts>
<n2:Formula>
<n2:ProbabilityFn>
<n2:RealNumber/>
</n2:ProbabilityFn>
<n2:decreasesLikelihood>
<n2:Formula/>
</n2:decreasesLikelihood>
<n2:independentProbability>
<n2:Formula/>
</n2:independentProbability>
<n2:increasesLikelihood>
<n2:Formula/>
</n2:increasesLikelihood>
<n2:modalAttribute>
<n2:NormativeAttribute/>
</n2:modalAttribute>
<n2:entails>
<n2:Formula/>
</n2:entails>
<n2:true>
<n2:TruthValue/>
</n2:true>
</n2:Formula>
</n1:doubts>
<n1:speaksLanguage>
<n2:Language>
<n2:expressedInLanguage>
<n2:Language/>
</n2:expressedInLanguage>
</n2:Language>
</n1:speaksLanguage>
</n2:CognitiveAgent>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization>
<n1:yearOfFounding>
<n2:Integer>
<n2:SuccessorFn>
<n2:Integer/>
</n2:SuccessorFn>
<n2:PredecessorFn>
<n2:Integer/>
</n2:PredecessorFn>
<n1:multiplicativeFactor>
<n2:Integer/>
</n1:multiplicativeFactor>
</n2:Integer>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea>
<n1:JudiciaryFn>
<n2:JudicialOrganization/>
</n1:JudiciaryFn>
<n1:dependentGeopoliticalArea>
<n2:GeopoliticalArea/>
</n1:dependentGeopoliticalArea>
<n1:totalGDP>
<n2:CurrencyMeasure/>
</n1:totalGDP>
<n1:CitizenryFn>
<n2:GroupOfPeople/>
</n1:CitizenryFn>
<n2:GovernmentFn>
<n2:Government/>
</n2:GovernmentFn>
<n1:currencyType>
<n2:CurrencyMeasure/>
</n1:currencyType>
<n1:legalSystemType>
<n1:LegalSystemAttribute/>
</n1:legalSystemType>
<n1:primaryGeopoliticalSubdivision>
<n2:GeopoliticalArea/>
</n1:primaryGeopoliticalSubdivision>
<n1:LegislatureFn>
<n1:LegislativeOrganization/>
</n1:LegislatureFn>
<n1:industryOfArea>
<n2:Physical/>
</n1:industryOfArea>
<n1:climateTypeInArea>
<n1:ClimateZone/>
</n1:climateTypeInArea>
<n1:financialAsset>
<n2:Object/>
</n1:financialAsset>
<n2:leader>
<n2:Human/>
</n2:leader>
<n1:economyType>
<n1:EconomicAttribute/>
</n1:economyType>
<n2:editor>
<n2:Text/>
</n2:editor>
<n2:authors>
<n2:Text/>
</n2:authors>
<n2:WealthFn>
<n2:CurrencyMeasure/>
</n2:WealthFn>
<n2:PropertyFn>
<n2:Set/>
</n2:PropertyFn>
<n1:ExecutiveBranchFn>
<n2:Organization/>
</n1:ExecutiveBranchFn>
<n1:customer>
<n2:Corporation/>
</n1:customer>
<n1:governmentType>
<n1:FormOfGovernment/>
</n1:governmentType>
<n1:leaderPosition>
<n2:Position/>
</n1:leaderPosition>
<n1:fiscalYearPeriod>
<n2:TimeInterval/>
</n1:fiscalYearPeriod>
</n2:GeopoliticalArea>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
<n1:teacher>
<n2:EducationalOrganization/>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy/>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent/>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object/>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess/>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction/>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent/>
</n1:allegiance>
<n1:disapproves>
<n2:Formula/>
</n1:disapproves>
<n2:wants>
<n2:Physical/>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction/>
</n1:plaintiff>
<n2:knows>
<n2:Formula/>
</n2:knows>
<n2:desires>
<n2:Formula/>
</n2:desires>
<n1:student>
<n2:EducationalOrganization/>
</n1:student>
<n2:considers>
<n2:Formula/>
</n2:considers>
<n1:doubts>
<n2:Formula/>
</n1:doubts>
</n2:Organization>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea>
<n1:JudiciaryFn>
<n2:JudicialOrganization/>
</n1:JudiciaryFn>
<n1:dependentGeopoliticalArea>
<n2:GeopoliticalArea/>
</n1:dependentGeopoliticalArea>
<n1:totalGDP>
<n2:CurrencyMeasure/>
</n1:totalGDP>
<n1:CitizenryFn>
<n2:GroupOfPeople/>
</n1:CitizenryFn>
<n2:GovernmentFn>
<n2:Government/>
</n2:GovernmentFn>
<n1:currencyType>
<n2:CurrencyMeasure/>
</n1:currencyType>
<n1:legalSystemType>
<n1:LegalSystemAttribute/>
</n1:legalSystemType>
<n1:primaryGeopoliticalSubdivision>
<n2:GeopoliticalArea/>
</n1:primaryGeopoliticalSubdivision>
<n1:LegislatureFn>
<n1:LegislativeOrganization/>
</n1:LegislatureFn>
<n1:industryOfArea>
<n2:Physical/>
</n1:industryOfArea>
<n1:climateTypeInArea>
<n1:ClimateZone/>
</n1:climateTypeInArea>
<n1:financialAsset>
<n2:Object/>
</n1:financialAsset>
<n2:leader>
<n2:Human/>
</n2:leader>
<n1:economyType>
<n1:EconomicAttribute/>
</n1:economyType>
<n2:editor>
<n2:Text/>
</n2:editor>
<n2:authors>
<n2:Text/>
</n2:authors>
<n2:WealthFn>
<n2:CurrencyMeasure/>
</n2:WealthFn>
<n2:PropertyFn>
<n2:Set/>
</n2:PropertyFn>
<n1:ExecutiveBranchFn>
<n2:Organization/>
</n1:ExecutiveBranchFn>
<n1:customer>
<n2:Corporation/>
</n1:customer>
<n1:governmentType>
<n1:FormOfGovernment/>
</n1:governmentType>
<n1:leaderPosition>
<n2:Position/>
</n1:leaderPosition>
<n1:fiscalYearPeriod>
<n2:TimeInterval/>
</n1:fiscalYearPeriod>
</n2:GeopoliticalArea>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text>
<n1:registeredItem>
<n2:Physical/>
</n1:registeredItem>
<n2:version>
<n2:Artifact/>
</n2:version>
<n1:equipmentType>
<n2:Device/>
</n1:equipmentType>
<n2:expressedInLanguage>
<n2:Language/>
</n2:expressedInLanguage>
</n2:Text>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent>
<n1:teacher>
<n2:EducationalOrganization/>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy/>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent/>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object/>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess/>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction/>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent/>
</n1:allegiance>
<n1:disapproves>
<n2:Formula/>
</n1:disapproves>
<n2:wants>
<n2:Physical/>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction/>
</n1:plaintiff>
<n2:knows>
<n2:Formula/>
</n2:knows>
<n2:desires>
<n2:Formula/>
</n2:desires>
<n1:student>
<n2:EducationalOrganization/>
</n1:student>
<n2:considers>
<n2:Formula/>
</n2:considers>
<n1:doubts>
<n2:Formula/>
</n1:doubts>
<n1:speaksLanguage>
<n2:Language/>
</n1:speaksLanguage>
</n2:CognitiveAgent>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
<n1:teacher>
<n2:EducationalOrganization/>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy/>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent/>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object/>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess/>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction/>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent/>
</n1:allegiance>
<n1:disapproves>
<n2:Formula/>
</n1:disapproves>
<n2:wants>
<n2:Physical/>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction/>
</n1:plaintiff>
<n2:knows>
<n2:Formula/>
</n2:knows>
<n2:desires>
<n2:Formula/>
</n2:desires>
<n1:student>
<n2:EducationalOrganization/>
</n1:student>
<n2:considers>
<n2:Formula/>
</n2:considers>
<n1:doubts>
<n2:Formula/>
</n1:doubts>
</n2:Organization>
</n1:ancestorOrganization>
<n1:teacher>
<n2:EducationalOrganization>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
</n2:EducationalOrganization>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy>
<n1:subField>
<n2:FieldOfStudy/>
</n1:subField>
<n2:consistent>
<n2:Proposition/>
</n2:consistent>
</n2:FieldOfStudy>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent>
<n1:teacher>
<n2:EducationalOrganization/>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy/>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent/>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object/>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess/>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction/>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent/>
</n1:allegiance>
<n1:disapproves>
<n2:Formula/>
</n1:disapproves>
<n2:wants>
<n2:Physical/>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction/>
</n1:plaintiff>
<n2:knows>
<n2:Formula/>
</n2:knows>
<n2:desires>
<n2:Formula/>
</n2:desires>
<n1:student>
<n2:EducationalOrganization/>
</n1:student>
<n2:considers>
<n2:Formula/>
</n2:considers>
<n1:doubts>
<n2:Formula/>
</n1:doubts>
<n1:speaksLanguage>
<n2:Language/>
</n1:speaksLanguage>
</n2:CognitiveAgent>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object>
<n2:larger>
<n2:Object/>
</n2:larger>
<n1:deviceState>
<n1:DeviceStateAttribute/>
</n1:deviceState>
<n2:faces>
<n2:DirectionalAttribute/>
</n2:faces>
<n1:older>
<n2:Object/>
</n1:older>
<n2:copy>
<n2:Object/>
</n2:copy>
<n2:uses>
<n2:Agent/>
</n2:uses>
<n2:linked>
<n2:Object/>
</n2:linked>
<n2:exploits>
<n2:Agent/>
</n2:exploits>
<n2:fills>
<n2:Hole/>
</n2:fills>
<n1:orbits>
<n2:AstronomicalBody/>
</n1:orbits>
<n1:barometricPressure>
<n1:AtmosphericPressureMeasure/>
</n1:barometricPressure>
<n2:smaller>
<n2:Object/>
</n2:smaller>
<n1:airTemperature>
<n2:TemperatureMeasure/>
</n1:airTemperature>
<n2:hasPurpose>
<n2:Formula/>
</n2:hasPurpose>
<n2:date>
<n2:Day/>
</n2:date>
<n2:WhenFn>
<n2:TimeInterval/>
</n2:WhenFn>
<n2:cooccur>
<n2:Physical/>
</n2:cooccur>
<n2:monetaryValue>
<n2:CurrencyMeasure/>
</n2:monetaryValue>
</n2:Object>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess>
<n2:subProcess>
<n2:Process/>
</n2:subProcess>
<n2:frequency>
<n2:TimeDuration/>
</n2:frequency>
<n2:realization>
<n2:Proposition/>
</n2:realization>
<n2:result>
<n2:Entity/>
</n2:result>
<n2:causesSubclass>
<n2:Process/>
</n2:causesSubclass>
<n2:inhibits>
<n2:Process/>
</n2:inhibits>
<n2:hasSkill>
<n2:Agent/>
</n2:hasSkill>
<n2:precondition>
<n2:Process/>
</n2:precondition>
<n2:causes>
<n2:Process/>
</n2:causes>
<n2:direction>
<n2:DirectionalAttribute/>
</n2:direction>
<n2:destination>
<n2:Entity/>
</n2:destination>
<n2:origin>
<n2:Object/>
</n2:origin>
<n1:targetInAttack>
<n2:Object/>
</n1:targetInAttack>
<n2:prevents>
<n2:Process/>
</n2:prevents>
</n2:IntentionalProcess>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction>
<n1:contestParticipant>
<n2:Agent/>
</n1:contestParticipant>
</n2:LegalAction>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent>
<n1:teacher>
<n2:EducationalOrganization/>
</n1:teacher>
<n1:hasExpertise>
<n2:FieldOfStudy/>
</n1:hasExpertise>
<n1:affiliatedOrganization>
<n2:CognitiveAgent/>
</n1:affiliatedOrganization>
<n1:dislikes>
<n2:Object/>
</n1:dislikes>
<n1:enjoys>
<n2:IntentionalProcess/>
</n1:enjoys>
<n1:defendant>
<n2:LegalAction/>
</n1:defendant>
<n1:allegiance>
<n2:CognitiveAgent/>
</n1:allegiance>
<n1:disapproves>
<n2:Formula/>
</n1:disapproves>
<n2:wants>
<n2:Physical/>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction/>
</n1:plaintiff>
<n2:knows>
<n2:Formula/>
</n2:knows>
<n2:desires>
<n2:Formula/>
</n2:desires>
<n1:student>
<n2:EducationalOrganization/>
</n1:student>
<n2:considers>
<n2:Formula/>
</n2:considers>
<n1:doubts>
<n2:Formula/>
</n1:doubts>
<n1:speaksLanguage>
<n2:Language/>
</n1:speaksLanguage>
</n2:CognitiveAgent>
</n1:allegiance>
<n1:disapproves>
<n2:Formula>
<n2:ProbabilityFn>
<n2:RealNumber/>
</n2:ProbabilityFn>
<n2:decreasesLikelihood>
<n2:Formula/>
</n2:decreasesLikelihood>
<n2:independentProbability>
<n2:Formula/>
</n2:independentProbability>
<n2:increasesLikelihood>
<n2:Formula/>
</n2:increasesLikelihood>
<n2:modalAttribute>
<n2:NormativeAttribute/>
</n2:modalAttribute>
<n2:entails>
<n2:Formula/>
</n2:entails>
<n2:true>
<n2:TruthValue/>
</n2:true>
</n2:Formula>
</n1:disapproves>
<n2:wants>
<n2:Physical>
<n2:hasPurpose>
<n2:Formula/>
</n2:hasPurpose>
<n2:date>
<n2:Day/>
</n2:date>
<n2:WhenFn>
<n2:TimeInterval/>
</n2:WhenFn>
<n2:cooccur>
<n2:Physical/>
</n2:cooccur>
<n2:monetaryValue>
<n2:CurrencyMeasure/>
</n2:monetaryValue>
</n2:Physical>
</n2:wants>
<n1:plaintiff>
<n2:LegalAction>
<n1:contestParticipant>
<n2:Agent/>
</n1:contestParticipant>
</n2:LegalAction>
</n1:plaintiff>
<n2:knows>
<n2:Formula>
<n2:ProbabilityFn>
<n2:RealNumber/>
</n2:ProbabilityFn>
<n2:decreasesLikelihood>
<n2:Formula/>
</n2:decreasesLikelihood>
<n2:independentProbability>
<n2:Formula/>
</n2:independentProbability>
<n2:increasesLikelihood>
<n2:Formula/>
</n2:increasesLikelihood>
<n2:modalAttribute>
<n2:NormativeAttribute/>
</n2:modalAttribute>
<n2:entails>
<n2:Formula/>
</n2:entails>
<n2:true>
<n2:TruthValue/>
</n2:true>
</n2:Formula>
</n2:knows>
<n2:desires>
<n2:Formula>
<n2:ProbabilityFn>
<n2:RealNumber/>
</n2:ProbabilityFn>
<n2:decreasesLikelihood>
<n2:Formula/>
</n2:decreasesLikelihood>
<n2:independentProbability>
<n2:Formula/>
</n2:independentProbability>
<n2:increasesLikelihood>
<n2:Formula/>
</n2:increasesLikelihood>
<n2:modalAttribute>
<n2:NormativeAttribute/>
</n2:modalAttribute>
<n2:entails>
<n2:Formula/>
</n2:entails>
<n2:true>
<n2:TruthValue/>
</n2:true>
</n2:Formula>
</n2:desires>
<n1:student>
<n2:EducationalOrganization>
<n1:yearOfFounding>
<n2:Integer/>
</n1:yearOfFounding>
<n1:religiousAffiliationOfOrganization>
<n2:BeliefGroup/>
</n1:religiousAffiliationOfOrganization>
<n1:agentOperatesInArea>
<n2:GeopoliticalArea/>
</n1:agentOperatesInArea>
<n2:subOrganization>
<n2:Organization/>
</n2:subOrganization>
<n1:ideologicalAffiliationOfOrganization>
<n1:FormOfGovernment/>
</n1:ideologicalAffiliationOfOrganization>
<n1:headquartersOfOrganization>
<n2:GeopoliticalArea/>
</n1:headquartersOfOrganization>
<n2:publishes>
<n2:Text/>
</n2:publishes>
<n2:employs>
<n2:CognitiveAgent/>
</n2:employs>
<n1:ancestorOrganization>
<n2:Organization/>
</n1:ancestorOrganization>
</n2:EducationalOrganization>
</n1:student>
<n2:considers>
<n2:Formula>
<n2:ProbabilityFn>
<n2:RealNumber/>
</n2:ProbabilityFn>
<n2:decreasesLikelihood>
<n2:Formula/>
</n2:decreasesLikelihood>
<n2:independentProbability>
<n2:Formula/>
</n2:independentProbability>
<n2:increasesLikelihood>
<n2:Formula/>
</n2:increasesLikelihood>
<n2:modalAttribute>
<n2:NormativeAttribute/>
</n2:modalAttribute>
<n2:entails>
<n2:Formula/>
</n2:entails>
<n2:true>
<n2:TruthValue/>
</n2:true>
</n2:Formula>
</n2:considers>
<n1:doubts>
<n2:Formula>
<n2:ProbabilityFn>
<n2:RealNumber/>
</n2:ProbabilityFn>
<n2:decreasesLikelihood>
<n2:Formula/>
</n2:decreasesLikelihood>
<n2:independentProbability>
<n2:Formula/>
</n2:independentProbability>
<n2:increasesLikelihood>
<n2:Formula/>
</n2:increasesLikelihood>
<n2:modalAttribute>
<n2:NormativeAttribute/>
</n2:modalAttribute>
<n2:entails>
<n2:Formula/>
</n2:entails>
<n2:true>
<n2:TruthValue/>
</n2:true>
</n2:Formula>
</n1:doubts>
</n2:Organization>
</n1:ancestorOrganization>
</n1:CareOrganization>
</rdf:RDF>
</xsl:template>
</xsl:transform>
