<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:n1="http://127.0.0.1:8000/ontology/SUMO.owl#" xmlns:n2="http://127.0.0.1:8000/ontology/Mid-level-ontology.owl#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:service="http://127.0.0.1:8000/services/OWLS-1.1/city_weathersystem_service.owls" version="2.0">
<xsl:output encoding="iso-8859-1" indent="yes" method="xml" version="1.0"/>
<xsl:template match="/">
<rdf:RDF>
<n1:City>
<n2:capitalCity>
<n1:GeopoliticalArea>
<n2:JudiciaryFn>
<n1:JudicialOrganization>
<n2:yearOfFounding>
<n1:Integer/>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea/>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization/>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea/>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text/>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent/>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization/>
</n2:ancestorOrganization>
</n1:JudicialOrganization>
</n2:JudiciaryFn>
<n2:dependentGeopoliticalArea>
<n1:GeopoliticalArea>
<n2:JudiciaryFn>
<n1:JudicialOrganization/>
</n2:JudiciaryFn>
<n2:dependentGeopoliticalArea>
<n1:GeopoliticalArea/>
</n2:dependentGeopoliticalArea>
<n2:totalGDP>
<n1:CurrencyMeasure/>
</n2:totalGDP>
<n2:CitizenryFn>
<n1:GroupOfPeople/>
</n2:CitizenryFn>
<n1:GovernmentFn>
<n1:Government/>
</n1:GovernmentFn>
<n2:currencyType>
<n1:CurrencyMeasure/>
</n2:currencyType>
<n2:legalSystemType>
<n2:LegalSystemAttribute/>
</n2:legalSystemType>
<n2:primaryGeopoliticalSubdivision>
<n1:GeopoliticalArea/>
</n2:primaryGeopoliticalSubdivision>
<n2:LegislatureFn>
<n2:LegislativeOrganization/>
</n2:LegislatureFn>
<n2:industryOfArea>
<n1:Physical/>
</n2:industryOfArea>
<n2:climateTypeInArea>
<n2:ClimateZone/>
</n2:climateTypeInArea>
<n2:financialAsset>
<n1:Object/>
</n2:financialAsset>
<n1:leader>
<n1:Human/>
</n1:leader>
<n2:economyType>
<n2:EconomicAttribute/>
</n2:economyType>
<n1:editor>
<n1:Text/>
</n1:editor>
<n1:authors>
<n1:Text/>
</n1:authors>
<n1:WealthFn>
<n1:CurrencyMeasure/>
</n1:WealthFn>
<n1:PropertyFn>
<n1:Set/>
</n1:PropertyFn>
<n2:ExecutiveBranchFn>
<n1:Organization/>
</n2:ExecutiveBranchFn>
<n2:customer>
<n1:Corporation/>
</n2:customer>
<n2:governmentType>
<n2:FormOfGovernment/>
</n2:governmentType>
<n2:leaderPosition>
<n1:Position/>
</n2:leaderPosition>
<n2:fiscalYearPeriod>
<n1:TimeInterval/>
</n2:fiscalYearPeriod>
</n1:GeopoliticalArea>
</n2:dependentGeopoliticalArea>
<n2:totalGDP>
<n1:CurrencyMeasure>
<n1:MagnitudeFn>
<n1:RealNumber/>
</n1:MagnitudeFn>
</n1:CurrencyMeasure>
</n2:totalGDP>
<n2:CitizenryFn>
<n1:GroupOfPeople/>
</n2:CitizenryFn>
<n1:GovernmentFn>
<n1:Government/>
</n1:GovernmentFn>
<n2:currencyType>
<n1:CurrencyMeasure>
<n1:MagnitudeFn>
<n1:RealNumber/>
</n1:MagnitudeFn>
</n1:CurrencyMeasure>
</n2:currencyType>
<n2:legalSystemType>
<n2:LegalSystemAttribute/>
</n2:legalSystemType>
<n2:primaryGeopoliticalSubdivision>
<n1:GeopoliticalArea>
<n2:JudiciaryFn>
<n1:JudicialOrganization/>
</n2:JudiciaryFn>
<n2:dependentGeopoliticalArea>
<n1:GeopoliticalArea/>
</n2:dependentGeopoliticalArea>
<n2:totalGDP>
<n1:CurrencyMeasure/>
</n2:totalGDP>
<n2:CitizenryFn>
<n1:GroupOfPeople/>
</n2:CitizenryFn>
<n1:GovernmentFn>
<n1:Government/>
</n1:GovernmentFn>
<n2:currencyType>
<n1:CurrencyMeasure/>
</n2:currencyType>
<n2:legalSystemType>
<n2:LegalSystemAttribute/>
</n2:legalSystemType>
<n2:primaryGeopoliticalSubdivision>
<n1:GeopoliticalArea/>
</n2:primaryGeopoliticalSubdivision>
<n2:LegislatureFn>
<n2:LegislativeOrganization/>
</n2:LegislatureFn>
<n2:industryOfArea>
<n1:Physical/>
</n2:industryOfArea>
<n2:climateTypeInArea>
<n2:ClimateZone/>
</n2:climateTypeInArea>
<n2:financialAsset>
<n1:Object/>
</n2:financialAsset>
<n1:leader>
<n1:Human/>
</n1:leader>
<n2:economyType>
<n2:EconomicAttribute/>
</n2:economyType>
<n1:editor>
<n1:Text/>
</n1:editor>
<n1:authors>
<n1:Text/>
</n1:authors>
<n1:WealthFn>
<n1:CurrencyMeasure/>
</n1:WealthFn>
<n1:PropertyFn>
<n1:Set/>
</n1:PropertyFn>
<n2:ExecutiveBranchFn>
<n1:Organization/>
</n2:ExecutiveBranchFn>
<n2:customer>
<n1:Corporation/>
</n2:customer>
<n2:governmentType>
<n2:FormOfGovernment/>
</n2:governmentType>
<n2:leaderPosition>
<n1:Position/>
</n2:leaderPosition>
<n2:fiscalYearPeriod>
<n1:TimeInterval/>
</n2:fiscalYearPeriod>
</n1:GeopoliticalArea>
</n2:primaryGeopoliticalSubdivision>
<n2:LegislatureFn>
<n2:LegislativeOrganization>
<n2:yearOfFounding>
<n1:Integer/>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea/>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization/>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea/>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text/>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent/>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization/>
</n2:ancestorOrganization>
</n2:LegislativeOrganization>
</n2:LegislatureFn>
<n2:industryOfArea>
<n1:Physical>
<n1:hasPurpose>
<n1:Formula/>
</n1:hasPurpose>
<n1:date>
<n1:Day/>
</n1:date>
<n1:WhenFn>
<n1:TimeInterval/>
</n1:WhenFn>
<n1:cooccur>
<n1:Physical/>
</n1:cooccur>
<n1:monetaryValue>
<n1:CurrencyMeasure/>
</n1:monetaryValue>
</n1:Physical>
</n2:industryOfArea>
<n2:climateTypeInArea>
<n2:ClimateZone>
<n2:climateTypeInArea>
<n2:ClimateZone/>
</n2:climateTypeInArea>
</n2:ClimateZone>
</n2:climateTypeInArea>
<n2:financialAsset>
<n1:Object>
<n1:larger>
<n1:Object/>
</n1:larger>
<n2:deviceState>
<n2:DeviceStateAttribute/>
</n2:deviceState>
<n1:faces>
<n1:DirectionalAttribute/>
</n1:faces>
<n2:older>
<n1:Object/>
</n2:older>
<n1:copy>
<n1:Object/>
</n1:copy>
<n1:uses>
<n1:Agent/>
</n1:uses>
<n1:linked>
<n1:Object/>
</n1:linked>
<n1:exploits>
<n1:Agent/>
</n1:exploits>
<n1:fills>
<n1:Hole/>
</n1:fills>
<n2:orbits>
<n1:AstronomicalBody/>
</n2:orbits>
<n2:barometricPressure>
<n2:AtmosphericPressureMeasure/>
</n2:barometricPressure>
<n1:smaller>
<n1:Object/>
</n1:smaller>
<n2:airTemperature>
<n1:TemperatureMeasure/>
</n2:airTemperature>
<n1:hasPurpose>
<n1:Formula/>
</n1:hasPurpose>
<n1:date>
<n1:Day/>
</n1:date>
<n1:WhenFn>
<n1:TimeInterval/>
</n1:WhenFn>
<n1:cooccur>
<n1:Physical/>
</n1:cooccur>
<n1:monetaryValue>
<n1:CurrencyMeasure/>
</n1:monetaryValue>
</n1:Object>
</n2:financialAsset>
<n1:leader>
<n1:Human>
<n2:intelligenceQuotient>
<n1:RationalNumber/>
</n2:intelligenceQuotient>
<n2:grandfather>
<n1:Man/>
</n2:grandfather>
<n1:citizen>
<n1:Nation/>
</n1:citizen>
<n1:ImmediateFamilyFn>
<n1:FamilyGroup/>
</n1:ImmediateFamilyFn>
<n2:birthday>
<n1:Day/>
</n2:birthday>
<n1:home>
<n1:PermanentResidence/>
</n1:home>
<n2:stepmother>
<n1:Woman/>
</n2:stepmother>
<n2:tenant>
<n1:Residence/>
</n2:tenant>
<n2:occupation>
<n1:FinancialTransaction/>
</n2:occupation>
<n2:groupMember>
<n1:GroupOfPeople/>
</n2:groupMember>
<n2:neighbor>
<n1:Human/>
</n2:neighbor>
<n2:DescendantsFn>
<n1:FamilyGroup/>
</n2:DescendantsFn>
<n2:grandmother>
<n1:Man/>
</n2:grandmother>
<n2:stepfather>
<n1:Man/>
</n2:stepfather>
<n2:cousin>
<n1:Human/>
</n2:cousin>
<n1:stays>
<n1:TemporaryResidence/>
</n1:stays>
<n2:patientMedical>
<n1:CognitiveAgent/>
</n2:patientMedical>
<n2:teacher>
<n1:EducationalOrganization/>
</n2:teacher>
<n2:hasExpertise>
<n1:FieldOfStudy/>
</n2:hasExpertise>
<n2:affiliatedOrganization>
<n1:CognitiveAgent/>
</n2:affiliatedOrganization>
<n2:dislikes>
<n1:Object/>
</n2:dislikes>
<n2:enjoys>
<n1:IntentionalProcess/>
</n2:enjoys>
<n2:defendant>
<n1:LegalAction/>
</n2:defendant>
<n2:allegiance>
<n1:CognitiveAgent/>
</n2:allegiance>
<n2:disapproves>
<n1:Formula/>
</n2:disapproves>
<n1:wants>
<n1:Physical/>
</n1:wants>
<n2:plaintiff>
<n1:LegalAction/>
</n2:plaintiff>
<n1:knows>
<n1:Formula/>
</n1:knows>
<n1:desires>
<n1:Formula/>
</n1:desires>
<n2:student>
<n1:EducationalOrganization/>
</n2:student>
<n1:considers>
<n1:Formula/>
</n1:considers>
<n2:doubts>
<n1:Formula/>
</n2:doubts>
</n1:Human>
</n1:leader>
<n2:economyType>
<n2:EconomicAttribute/>
</n2:economyType>
<n1:editor>
<n1:Text>
<n2:registeredItem>
<n1:Physical/>
</n2:registeredItem>
<n1:version>
<n1:Artifact/>
</n1:version>
<n2:equipmentType>
<n1:Device/>
</n2:equipmentType>
<n1:expressedInLanguage>
<n1:Language/>
</n1:expressedInLanguage>
</n1:Text>
</n1:editor>
<n1:authors>
<n1:Text>
<n2:registeredItem>
<n1:Physical/>
</n2:registeredItem>
<n1:version>
<n1:Artifact/>
</n1:version>
<n2:equipmentType>
<n1:Device/>
</n2:equipmentType>
<n1:expressedInLanguage>
<n1:Language/>
</n1:expressedInLanguage>
</n1:Text>
</n1:authors>
<n1:WealthFn>
<n1:CurrencyMeasure>
<n1:MagnitudeFn>
<n1:RealNumber/>
</n1:MagnitudeFn>
</n1:CurrencyMeasure>
</n1:WealthFn>
<n1:PropertyFn>
<n1:Set>
<n1:subset>
<n1:Set/>
</n1:subset>
<n1:ComplementFn>
<n1:SetOrClass/>
</n1:ComplementFn>
<n1:GeneralizedIntersectionFn>
<n1:SetOrClass/>
</n1:GeneralizedIntersectionFn>
<n1:GeneralizedUnionFn>
<n1:SetOrClass/>
</n1:GeneralizedUnionFn>
<n1:disjoint>
<n1:SetOrClass/>
</n1:disjoint>
</n1:Set>
</n1:PropertyFn>
<n2:ExecutiveBranchFn>
<n1:Organization>
<n2:yearOfFounding>
<n1:Integer/>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea/>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization/>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea/>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text/>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent/>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization/>
</n2:ancestorOrganization>
<n2:teacher>
<n1:EducationalOrganization/>
</n2:teacher>
<n2:hasExpertise>
<n1:FieldOfStudy/>
</n2:hasExpertise>
<n2:affiliatedOrganization>
<n1:CognitiveAgent/>
</n2:affiliatedOrganization>
<n2:dislikes>
<n1:Object/>
</n2:dislikes>
<n2:enjoys>
<n1:IntentionalProcess/>
</n2:enjoys>
<n2:defendant>
<n1:LegalAction/>
</n2:defendant>
<n2:allegiance>
<n1:CognitiveAgent/>
</n2:allegiance>
<n2:disapproves>
<n1:Formula/>
</n2:disapproves>
<n1:wants>
<n1:Physical/>
</n1:wants>
<n2:plaintiff>
<n1:LegalAction/>
</n2:plaintiff>
<n1:knows>
<n1:Formula/>
</n1:knows>
<n1:desires>
<n1:Formula/>
</n1:desires>
<n2:student>
<n1:EducationalOrganization/>
</n2:student>
<n1:considers>
<n1:Formula/>
</n1:considers>
<n2:doubts>
<n1:Formula/>
</n2:doubts>
</n1:Organization>
</n2:ExecutiveBranchFn>
<n2:customer>
<n1:Corporation>
<n2:yearOfFounding>
<n1:Integer/>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea/>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization/>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea/>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text/>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent/>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization/>
</n2:ancestorOrganization>
</n1:Corporation>
</n2:customer>
<n2:governmentType>
<n2:FormOfGovernment/>
</n2:governmentType>
<n2:leaderPosition>
<n1:Position/>
</n2:leaderPosition>
<n2:fiscalYearPeriod>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n2:fiscalYearPeriod>
</n1:GeopoliticalArea>
</n2:capitalCity>
<n2:cityAddress>
<n2:Address/>
</n2:cityAddress>
<n2:JudiciaryFn>
<n1:JudicialOrganization>
<n2:yearOfFounding>
<n1:Integer>
<n1:SuccessorFn>
<n1:Integer/>
</n1:SuccessorFn>
<n1:PredecessorFn>
<n1:Integer/>
</n1:PredecessorFn>
<n2:multiplicativeFactor>
<n1:Integer/>
</n2:multiplicativeFactor>
</n1:Integer>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea>
<n2:JudiciaryFn>
<n1:JudicialOrganization/>
</n2:JudiciaryFn>
<n2:dependentGeopoliticalArea>
<n1:GeopoliticalArea/>
</n2:dependentGeopoliticalArea>
<n2:totalGDP>
<n1:CurrencyMeasure/>
</n2:totalGDP>
<n2:CitizenryFn>
<n1:GroupOfPeople/>
</n2:CitizenryFn>
<n1:GovernmentFn>
<n1:Government/>
</n1:GovernmentFn>
<n2:currencyType>
<n1:CurrencyMeasure/>
</n2:currencyType>
<n2:legalSystemType>
<n2:LegalSystemAttribute/>
</n2:legalSystemType>
<n2:primaryGeopoliticalSubdivision>
<n1:GeopoliticalArea/>
</n2:primaryGeopoliticalSubdivision>
<n2:LegislatureFn>
<n2:LegislativeOrganization/>
</n2:LegislatureFn>
<n2:industryOfArea>
<n1:Physical/>
</n2:industryOfArea>
<n2:climateTypeInArea>
<n2:ClimateZone/>
</n2:climateTypeInArea>
<n2:financialAsset>
<n1:Object/>
</n2:financialAsset>
<n1:leader>
<n1:Human/>
</n1:leader>
<n2:economyType>
<n2:EconomicAttribute/>
</n2:economyType>
<n1:editor>
<n1:Text/>
</n1:editor>
<n1:authors>
<n1:Text/>
</n1:authors>
<n1:WealthFn>
<n1:CurrencyMeasure/>
</n1:WealthFn>
<n1:PropertyFn>
<n1:Set/>
</n1:PropertyFn>
<n2:ExecutiveBranchFn>
<n1:Organization/>
</n2:ExecutiveBranchFn>
<n2:customer>
<n1:Corporation/>
</n2:customer>
<n2:governmentType>
<n2:FormOfGovernment/>
</n2:governmentType>
<n2:leaderPosition>
<n1:Position/>
</n2:leaderPosition>
<n2:fiscalYearPeriod>
<n1:TimeInterval/>
</n2:fiscalYearPeriod>
</n1:GeopoliticalArea>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization>
<n2:yearOfFounding>
<n1:Integer/>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea/>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization/>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea/>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text/>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent/>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization/>
</n2:ancestorOrganization>
<n2:teacher>
<n1:EducationalOrganization/>
</n2:teacher>
<n2:hasExpertise>
<n1:FieldOfStudy/>
</n2:hasExpertise>
<n2:affiliatedOrganization>
<n1:CognitiveAgent/>
</n2:affiliatedOrganization>
<n2:dislikes>
<n1:Object/>
</n2:dislikes>
<n2:enjoys>
<n1:IntentionalProcess/>
</n2:enjoys>
<n2:defendant>
<n1:LegalAction/>
</n2:defendant>
<n2:allegiance>
<n1:CognitiveAgent/>
</n2:allegiance>
<n2:disapproves>
<n1:Formula/>
</n2:disapproves>
<n1:wants>
<n1:Physical/>
</n1:wants>
<n2:plaintiff>
<n1:LegalAction/>
</n2:plaintiff>
<n1:knows>
<n1:Formula/>
</n1:knows>
<n1:desires>
<n1:Formula/>
</n1:desires>
<n2:student>
<n1:EducationalOrganization/>
</n2:student>
<n1:considers>
<n1:Formula/>
</n1:considers>
<n2:doubts>
<n1:Formula/>
</n2:doubts>
</n1:Organization>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea>
<n2:JudiciaryFn>
<n1:JudicialOrganization/>
</n2:JudiciaryFn>
<n2:dependentGeopoliticalArea>
<n1:GeopoliticalArea/>
</n2:dependentGeopoliticalArea>
<n2:totalGDP>
<n1:CurrencyMeasure/>
</n2:totalGDP>
<n2:CitizenryFn>
<n1:GroupOfPeople/>
</n2:CitizenryFn>
<n1:GovernmentFn>
<n1:Government/>
</n1:GovernmentFn>
<n2:currencyType>
<n1:CurrencyMeasure/>
</n2:currencyType>
<n2:legalSystemType>
<n2:LegalSystemAttribute/>
</n2:legalSystemType>
<n2:primaryGeopoliticalSubdivision>
<n1:GeopoliticalArea/>
</n2:primaryGeopoliticalSubdivision>
<n2:LegislatureFn>
<n2:LegislativeOrganization/>
</n2:LegislatureFn>
<n2:industryOfArea>
<n1:Physical/>
</n2:industryOfArea>
<n2:climateTypeInArea>
<n2:ClimateZone/>
</n2:climateTypeInArea>
<n2:financialAsset>
<n1:Object/>
</n2:financialAsset>
<n1:leader>
<n1:Human/>
</n1:leader>
<n2:economyType>
<n2:EconomicAttribute/>
</n2:economyType>
<n1:editor>
<n1:Text/>
</n1:editor>
<n1:authors>
<n1:Text/>
</n1:authors>
<n1:WealthFn>
<n1:CurrencyMeasure/>
</n1:WealthFn>
<n1:PropertyFn>
<n1:Set/>
</n1:PropertyFn>
<n2:ExecutiveBranchFn>
<n1:Organization/>
</n2:ExecutiveBranchFn>
<n2:customer>
<n1:Corporation/>
</n2:customer>
<n2:governmentType>
<n2:FormOfGovernment/>
</n2:governmentType>
<n2:leaderPosition>
<n1:Position/>
</n2:leaderPosition>
<n2:fiscalYearPeriod>
<n1:TimeInterval/>
</n2:fiscalYearPeriod>
</n1:GeopoliticalArea>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text>
<n2:registeredItem>
<n1:Physical/>
</n2:registeredItem>
<n1:version>
<n1:Artifact/>
</n1:version>
<n2:equipmentType>
<n1:Device/>
</n2:equipmentType>
<n1:expressedInLanguage>
<n1:Language/>
</n1:expressedInLanguage>
</n1:Text>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent>
<n2:teacher>
<n1:EducationalOrganization/>
</n2:teacher>
<n2:hasExpertise>
<n1:FieldOfStudy/>
</n2:hasExpertise>
<n2:affiliatedOrganization>
<n1:CognitiveAgent/>
</n2:affiliatedOrganization>
<n2:dislikes>
<n1:Object/>
</n2:dislikes>
<n2:enjoys>
<n1:IntentionalProcess/>
</n2:enjoys>
<n2:defendant>
<n1:LegalAction/>
</n2:defendant>
<n2:allegiance>
<n1:CognitiveAgent/>
</n2:allegiance>
<n2:disapproves>
<n1:Formula/>
</n2:disapproves>
<n1:wants>
<n1:Physical/>
</n1:wants>
<n2:plaintiff>
<n1:LegalAction/>
</n2:plaintiff>
<n1:knows>
<n1:Formula/>
</n1:knows>
<n1:desires>
<n1:Formula/>
</n1:desires>
<n2:student>
<n1:EducationalOrganization/>
</n2:student>
<n1:considers>
<n1:Formula/>
</n1:considers>
<n2:doubts>
<n1:Formula/>
</n2:doubts>
<n2:speaksLanguage>
<n1:Language/>
</n2:speaksLanguage>
</n1:CognitiveAgent>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization>
<n2:yearOfFounding>
<n1:Integer/>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea/>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization/>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea/>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text/>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent/>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization/>
</n2:ancestorOrganization>
<n2:teacher>
<n1:EducationalOrganization/>
</n2:teacher>
<n2:hasExpertise>
<n1:FieldOfStudy/>
</n2:hasExpertise>
<n2:affiliatedOrganization>
<n1:CognitiveAgent/>
</n2:affiliatedOrganization>
<n2:dislikes>
<n1:Object/>
</n2:dislikes>
<n2:enjoys>
<n1:IntentionalProcess/>
</n2:enjoys>
<n2:defendant>
<n1:LegalAction/>
</n2:defendant>
<n2:allegiance>
<n1:CognitiveAgent/>
</n2:allegiance>
<n2:disapproves>
<n1:Formula/>
</n2:disapproves>
<n1:wants>
<n1:Physical/>
</n1:wants>
<n2:plaintiff>
<n1:LegalAction/>
</n2:plaintiff>
<n1:knows>
<n1:Formula/>
</n1:knows>
<n1:desires>
<n1:Formula/>
</n1:desires>
<n2:student>
<n1:EducationalOrganization/>
</n2:student>
<n1:considers>
<n1:Formula/>
</n1:considers>
<n2:doubts>
<n1:Formula/>
</n2:doubts>
</n1:Organization>
</n2:ancestorOrganization>
</n1:JudicialOrganization>
</n2:JudiciaryFn>
<n2:dependentGeopoliticalArea>
<n1:GeopoliticalArea>
<n2:JudiciaryFn>
<n1:JudicialOrganization>
<n2:yearOfFounding>
<n1:Integer/>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea/>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization/>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea/>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text/>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent/>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization/>
</n2:ancestorOrganization>
</n1:JudicialOrganization>
</n2:JudiciaryFn>
<n2:dependentGeopoliticalArea>
<n1:GeopoliticalArea>
<n2:JudiciaryFn>
<n1:JudicialOrganization/>
</n2:JudiciaryFn>
<n2:dependentGeopoliticalArea>
<n1:GeopoliticalArea/>
</n2:dependentGeopoliticalArea>
<n2:totalGDP>
<n1:CurrencyMeasure/>
</n2:totalGDP>
<n2:CitizenryFn>
<n1:GroupOfPeople/>
</n2:CitizenryFn>
<n1:GovernmentFn>
<n1:Government/>
</n1:GovernmentFn>
<n2:currencyType>
<n1:CurrencyMeasure/>
</n2:currencyType>
<n2:legalSystemType>
<n2:LegalSystemAttribute/>
</n2:legalSystemType>
<n2:primaryGeopoliticalSubdivision>
<n1:GeopoliticalArea/>
</n2:primaryGeopoliticalSubdivision>
<n2:LegislatureFn>
<n2:LegislativeOrganization/>
</n2:LegislatureFn>
<n2:industryOfArea>
<n1:Physical/>
</n2:industryOfArea>
<n2:climateTypeInArea>
<n2:ClimateZone/>
</n2:climateTypeInArea>
<n2:financialAsset>
<n1:Object/>
</n2:financialAsset>
<n1:leader>
<n1:Human/>
</n1:leader>
<n2:economyType>
<n2:EconomicAttribute/>
</n2:economyType>
<n1:editor>
<n1:Text/>
</n1:editor>
<n1:authors>
<n1:Text/>
</n1:authors>
<n1:WealthFn>
<n1:CurrencyMeasure/>
</n1:WealthFn>
<n1:PropertyFn>
<n1:Set/>
</n1:PropertyFn>
<n2:ExecutiveBranchFn>
<n1:Organization/>
</n2:ExecutiveBranchFn>
<n2:customer>
<n1:Corporation/>
</n2:customer>
<n2:governmentType>
<n2:FormOfGovernment/>
</n2:governmentType>
<n2:leaderPosition>
<n1:Position/>
</n2:leaderPosition>
<n2:fiscalYearPeriod>
<n1:TimeInterval/>
</n2:fiscalYearPeriod>
</n1:GeopoliticalArea>
</n2:dependentGeopoliticalArea>
<n2:totalGDP>
<n1:CurrencyMeasure>
<n1:MagnitudeFn>
<n1:RealNumber/>
</n1:MagnitudeFn>
</n1:CurrencyMeasure>
</n2:totalGDP>
<n2:CitizenryFn>
<n1:GroupOfPeople/>
</n2:CitizenryFn>
<n1:GovernmentFn>
<n1:Government/>
</n1:GovernmentFn>
<n2:currencyType>
<n1:CurrencyMeasure>
<n1:MagnitudeFn>
<n1:RealNumber/>
</n1:MagnitudeFn>
</n1:CurrencyMeasure>
</n2:currencyType>
<n2:legalSystemType>
<n2:LegalSystemAttribute/>
</n2:legalSystemType>
<n2:primaryGeopoliticalSubdivision>
<n1:GeopoliticalArea>
<n2:JudiciaryFn>
<n1:JudicialOrganization/>
</n2:JudiciaryFn>
<n2:dependentGeopoliticalArea>
<n1:GeopoliticalArea/>
</n2:dependentGeopoliticalArea>
<n2:totalGDP>
<n1:CurrencyMeasure/>
</n2:totalGDP>
<n2:CitizenryFn>
<n1:GroupOfPeople/>
</n2:CitizenryFn>
<n1:GovernmentFn>
<n1:Government/>
</n1:GovernmentFn>
<n2:currencyType>
<n1:CurrencyMeasure/>
</n2:currencyType>
<n2:legalSystemType>
<n2:LegalSystemAttribute/>
</n2:legalSystemType>
<n2:primaryGeopoliticalSubdivision>
<n1:GeopoliticalArea/>
</n2:primaryGeopoliticalSubdivision>
<n2:LegislatureFn>
<n2:LegislativeOrganization/>
</n2:LegislatureFn>
<n2:industryOfArea>
<n1:Physical/>
</n2:industryOfArea>
<n2:climateTypeInArea>
<n2:ClimateZone/>
</n2:climateTypeInArea>
<n2:financialAsset>
<n1:Object/>
</n2:financialAsset>
<n1:leader>
<n1:Human/>
</n1:leader>
<n2:economyType>
<n2:EconomicAttribute/>
</n2:economyType>
<n1:editor>
<n1:Text/>
</n1:editor>
<n1:authors>
<n1:Text/>
</n1:authors>
<n1:WealthFn>
<n1:CurrencyMeasure/>
</n1:WealthFn>
<n1:PropertyFn>
<n1:Set/>
</n1:PropertyFn>
<n2:ExecutiveBranchFn>
<n1:Organization/>
</n2:ExecutiveBranchFn>
<n2:customer>
<n1:Corporation/>
</n2:customer>
<n2:governmentType>
<n2:FormOfGovernment/>
</n2:governmentType>
<n2:leaderPosition>
<n1:Position/>
</n2:leaderPosition>
<n2:fiscalYearPeriod>
<n1:TimeInterval/>
</n2:fiscalYearPeriod>
</n1:GeopoliticalArea>
</n2:primaryGeopoliticalSubdivision>
<n2:LegislatureFn>
<n2:LegislativeOrganization>
<n2:yearOfFounding>
<n1:Integer/>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea/>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization/>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea/>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text/>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent/>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization/>
</n2:ancestorOrganization>
</n2:LegislativeOrganization>
</n2:LegislatureFn>
<n2:industryOfArea>
<n1:Physical>
<n1:hasPurpose>
<n1:Formula/>
</n1:hasPurpose>
<n1:date>
<n1:Day/>
</n1:date>
<n1:WhenFn>
<n1:TimeInterval/>
</n1:WhenFn>
<n1:cooccur>
<n1:Physical/>
</n1:cooccur>
<n1:monetaryValue>
<n1:CurrencyMeasure/>
</n1:monetaryValue>
</n1:Physical>
</n2:industryOfArea>
<n2:climateTypeInArea>
<n2:ClimateZone>
<n2:climateTypeInArea>
<n2:ClimateZone/>
</n2:climateTypeInArea>
</n2:ClimateZone>
</n2:climateTypeInArea>
<n2:financialAsset>
<n1:Object>
<n1:larger>
<n1:Object/>
</n1:larger>
<n2:deviceState>
<n2:DeviceStateAttribute/>
</n2:deviceState>
<n1:faces>
<n1:DirectionalAttribute/>
</n1:faces>
<n2:older>
<n1:Object/>
</n2:older>
<n1:copy>
<n1:Object/>
</n1:copy>
<n1:uses>
<n1:Agent/>
</n1:uses>
<n1:linked>
<n1:Object/>
</n1:linked>
<n1:exploits>
<n1:Agent/>
</n1:exploits>
<n1:fills>
<n1:Hole/>
</n1:fills>
<n2:orbits>
<n1:AstronomicalBody/>
</n2:orbits>
<n2:barometricPressure>
<n2:AtmosphericPressureMeasure/>
</n2:barometricPressure>
<n1:smaller>
<n1:Object/>
</n1:smaller>
<n2:airTemperature>
<n1:TemperatureMeasure/>
</n2:airTemperature>
<n1:hasPurpose>
<n1:Formula/>
</n1:hasPurpose>
<n1:date>
<n1:Day/>
</n1:date>
<n1:WhenFn>
<n1:TimeInterval/>
</n1:WhenFn>
<n1:cooccur>
<n1:Physical/>
</n1:cooccur>
<n1:monetaryValue>
<n1:CurrencyMeasure/>
</n1:monetaryValue>
</n1:Object>
</n2:financialAsset>
<n1:leader>
<n1:Human>
<n2:intelligenceQuotient>
<n1:RationalNumber/>
</n2:intelligenceQuotient>
<n2:grandfather>
<n1:Man/>
</n2:grandfather>
<n1:citizen>
<n1:Nation/>
</n1:citizen>
<n1:ImmediateFamilyFn>
<n1:FamilyGroup/>
</n1:ImmediateFamilyFn>
<n2:birthday>
<n1:Day/>
</n2:birthday>
<n1:home>
<n1:PermanentResidence/>
</n1:home>
<n2:stepmother>
<n1:Woman/>
</n2:stepmother>
<n2:tenant>
<n1:Residence/>
</n2:tenant>
<n2:occupation>
<n1:FinancialTransaction/>
</n2:occupation>
<n2:groupMember>
<n1:GroupOfPeople/>
</n2:groupMember>
<n2:neighbor>
<n1:Human/>
</n2:neighbor>
<n2:DescendantsFn>
<n1:FamilyGroup/>
</n2:DescendantsFn>
<n2:grandmother>
<n1:Man/>
</n2:grandmother>
<n2:stepfather>
<n1:Man/>
</n2:stepfather>
<n2:cousin>
<n1:Human/>
</n2:cousin>
<n1:stays>
<n1:TemporaryResidence/>
</n1:stays>
<n2:patientMedical>
<n1:CognitiveAgent/>
</n2:patientMedical>
<n2:teacher>
<n1:EducationalOrganization/>
</n2:teacher>
<n2:hasExpertise>
<n1:FieldOfStudy/>
</n2:hasExpertise>
<n2:affiliatedOrganization>
<n1:CognitiveAgent/>
</n2:affiliatedOrganization>
<n2:dislikes>
<n1:Object/>
</n2:dislikes>
<n2:enjoys>
<n1:IntentionalProcess/>
</n2:enjoys>
<n2:defendant>
<n1:LegalAction/>
</n2:defendant>
<n2:allegiance>
<n1:CognitiveAgent/>
</n2:allegiance>
<n2:disapproves>
<n1:Formula/>
</n2:disapproves>
<n1:wants>
<n1:Physical/>
</n1:wants>
<n2:plaintiff>
<n1:LegalAction/>
</n2:plaintiff>
<n1:knows>
<n1:Formula/>
</n1:knows>
<n1:desires>
<n1:Formula/>
</n1:desires>
<n2:student>
<n1:EducationalOrganization/>
</n2:student>
<n1:considers>
<n1:Formula/>
</n1:considers>
<n2:doubts>
<n1:Formula/>
</n2:doubts>
</n1:Human>
</n1:leader>
<n2:economyType>
<n2:EconomicAttribute/>
</n2:economyType>
<n1:editor>
<n1:Text>
<n2:registeredItem>
<n1:Physical/>
</n2:registeredItem>
<n1:version>
<n1:Artifact/>
</n1:version>
<n2:equipmentType>
<n1:Device/>
</n2:equipmentType>
<n1:expressedInLanguage>
<n1:Language/>
</n1:expressedInLanguage>
</n1:Text>
</n1:editor>
<n1:authors>
<n1:Text>
<n2:registeredItem>
<n1:Physical/>
</n2:registeredItem>
<n1:version>
<n1:Artifact/>
</n1:version>
<n2:equipmentType>
<n1:Device/>
</n2:equipmentType>
<n1:expressedInLanguage>
<n1:Language/>
</n1:expressedInLanguage>
</n1:Text>
</n1:authors>
<n1:WealthFn>
<n1:CurrencyMeasure>
<n1:MagnitudeFn>
<n1:RealNumber/>
</n1:MagnitudeFn>
</n1:CurrencyMeasure>
</n1:WealthFn>
<n1:PropertyFn>
<n1:Set>
<n1:subset>
<n1:Set/>
</n1:subset>
<n1:ComplementFn>
<n1:SetOrClass/>
</n1:ComplementFn>
<n1:GeneralizedIntersectionFn>
<n1:SetOrClass/>
</n1:GeneralizedIntersectionFn>
<n1:GeneralizedUnionFn>
<n1:SetOrClass/>
</n1:GeneralizedUnionFn>
<n1:disjoint>
<n1:SetOrClass/>
</n1:disjoint>
</n1:Set>
</n1:PropertyFn>
<n2:ExecutiveBranchFn>
<n1:Organization>
<n2:yearOfFounding>
<n1:Integer/>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea/>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization/>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea/>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text/>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent/>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization/>
</n2:ancestorOrganization>
<n2:teacher>
<n1:EducationalOrganization/>
</n2:teacher>
<n2:hasExpertise>
<n1:FieldOfStudy/>
</n2:hasExpertise>
<n2:affiliatedOrganization>
<n1:CognitiveAgent/>
</n2:affiliatedOrganization>
<n2:dislikes>
<n1:Object/>
</n2:dislikes>
<n2:enjoys>
<n1:IntentionalProcess/>
</n2:enjoys>
<n2:defendant>
<n1:LegalAction/>
</n2:defendant>
<n2:allegiance>
<n1:CognitiveAgent/>
</n2:allegiance>
<n2:disapproves>
<n1:Formula/>
</n2:disapproves>
<n1:wants>
<n1:Physical/>
</n1:wants>
<n2:plaintiff>
<n1:LegalAction/>
</n2:plaintiff>
<n1:knows>
<n1:Formula/>
</n1:knows>
<n1:desires>
<n1:Formula/>
</n1:desires>
<n2:student>
<n1:EducationalOrganization/>
</n2:student>
<n1:considers>
<n1:Formula/>
</n1:considers>
<n2:doubts>
<n1:Formula/>
</n2:doubts>
</n1:Organization>
</n2:ExecutiveBranchFn>
<n2:customer>
<n1:Corporation>
<n2:yearOfFounding>
<n1:Integer/>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea/>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization/>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea/>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text/>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent/>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization/>
</n2:ancestorOrganization>
</n1:Corporation>
</n2:customer>
<n2:governmentType>
<n2:FormOfGovernment/>
</n2:governmentType>
<n2:leaderPosition>
<n1:Position/>
</n2:leaderPosition>
<n2:fiscalYearPeriod>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n2:fiscalYearPeriod>
</n1:GeopoliticalArea>
</n2:dependentGeopoliticalArea>
<n2:totalGDP>
<n1:CurrencyMeasure>
<n1:MagnitudeFn>
<n1:RealNumber>
<n1:CeilingFn>
<n1:Integer/>
</n1:CeilingFn>
<n1:IntegerSquareRootFn>
<n1:NonnegativeInteger/>
</n1:IntegerSquareRootFn>
<n1:FloorFn>
<n1:Integer/>
</n1:FloorFn>
<n1:SignumFn>
<n1:Integer/>
</n1:SignumFn>
<n1:NumeratorFn>
<n1:Integer/>
</n1:NumeratorFn>
<n1:SquareRootFn>
<n1:Number/>
</n1:SquareRootFn>
<n1:AbsoluteValueFn>
<n1:NonnegativeRealNumber/>
</n1:AbsoluteValueFn>
<n1:DenominatorFn>
<n1:Integer/>
</n1:DenominatorFn>
<n1:RealNumberFn>
<n1:RealNumber/>
</n1:RealNumberFn>
<n1:RationalNumberFn>
<n1:RationalNumber/>
</n1:RationalNumberFn>
</n1:RealNumber>
</n1:MagnitudeFn>
</n1:CurrencyMeasure>
</n2:totalGDP>
<n2:CitizenryFn>
<n1:GroupOfPeople/>
</n2:CitizenryFn>
<n1:GovernmentFn>
<n1:Government/>
</n1:GovernmentFn>
<n2:currencyType>
<n1:CurrencyMeasure>
<n1:MagnitudeFn>
<n1:RealNumber>
<n1:CeilingFn>
<n1:Integer/>
</n1:CeilingFn>
<n1:IntegerSquareRootFn>
<n1:NonnegativeInteger/>
</n1:IntegerSquareRootFn>
<n1:FloorFn>
<n1:Integer/>
</n1:FloorFn>
<n1:SignumFn>
<n1:Integer/>
</n1:SignumFn>
<n1:NumeratorFn>
<n1:Integer/>
</n1:NumeratorFn>
<n1:SquareRootFn>
<n1:Number/>
</n1:SquareRootFn>
<n1:AbsoluteValueFn>
<n1:NonnegativeRealNumber/>
</n1:AbsoluteValueFn>
<n1:DenominatorFn>
<n1:Integer/>
</n1:DenominatorFn>
<n1:RealNumberFn>
<n1:RealNumber/>
</n1:RealNumberFn>
<n1:RationalNumberFn>
<n1:RationalNumber/>
</n1:RationalNumberFn>
</n1:RealNumber>
</n1:MagnitudeFn>
</n1:CurrencyMeasure>
</n2:currencyType>
<n2:legalSystemType>
<n2:LegalSystemAttribute/>
</n2:legalSystemType>
<n2:primaryGeopoliticalSubdivision>
<n1:GeopoliticalArea>
<n2:JudiciaryFn>
<n1:JudicialOrganization>
<n2:yearOfFounding>
<n1:Integer/>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea/>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization/>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea/>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text/>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent/>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization/>
</n2:ancestorOrganization>
</n1:JudicialOrganization>
</n2:JudiciaryFn>
<n2:dependentGeopoliticalArea>
<n1:GeopoliticalArea>
<n2:JudiciaryFn>
<n1:JudicialOrganization/>
</n2:JudiciaryFn>
<n2:dependentGeopoliticalArea>
<n1:GeopoliticalArea/>
</n2:dependentGeopoliticalArea>
<n2:totalGDP>
<n1:CurrencyMeasure/>
</n2:totalGDP>
<n2:CitizenryFn>
<n1:GroupOfPeople/>
</n2:CitizenryFn>
<n1:GovernmentFn>
<n1:Government/>
</n1:GovernmentFn>
<n2:currencyType>
<n1:CurrencyMeasure/>
</n2:currencyType>
<n2:legalSystemType>
<n2:LegalSystemAttribute/>
</n2:legalSystemType>
<n2:primaryGeopoliticalSubdivision>
<n1:GeopoliticalArea/>
</n2:primaryGeopoliticalSubdivision>
<n2:LegislatureFn>
<n2:LegislativeOrganization/>
</n2:LegislatureFn>
<n2:industryOfArea>
<n1:Physical/>
</n2:industryOfArea>
<n2:climateTypeInArea>
<n2:ClimateZone/>
</n2:climateTypeInArea>
<n2:financialAsset>
<n1:Object/>
</n2:financialAsset>
<n1:leader>
<n1:Human/>
</n1:leader>
<n2:economyType>
<n2:EconomicAttribute/>
</n2:economyType>
<n1:editor>
<n1:Text/>
</n1:editor>
<n1:authors>
<n1:Text/>
</n1:authors>
<n1:WealthFn>
<n1:CurrencyMeasure/>
</n1:WealthFn>
<n1:PropertyFn>
<n1:Set/>
</n1:PropertyFn>
<n2:ExecutiveBranchFn>
<n1:Organization/>
</n2:ExecutiveBranchFn>
<n2:customer>
<n1:Corporation/>
</n2:customer>
<n2:governmentType>
<n2:FormOfGovernment/>
</n2:governmentType>
<n2:leaderPosition>
<n1:Position/>
</n2:leaderPosition>
<n2:fiscalYearPeriod>
<n1:TimeInterval/>
</n2:fiscalYearPeriod>
</n1:GeopoliticalArea>
</n2:dependentGeopoliticalArea>
<n2:totalGDP>
<n1:CurrencyMeasure>
<n1:MagnitudeFn>
<n1:RealNumber/>
</n1:MagnitudeFn>
</n1:CurrencyMeasure>
</n2:totalGDP>
<n2:CitizenryFn>
<n1:GroupOfPeople/>
</n2:CitizenryFn>
<n1:GovernmentFn>
<n1:Government/>
</n1:GovernmentFn>
<n2:currencyType>
<n1:CurrencyMeasure>
<n1:MagnitudeFn>
<n1:RealNumber/>
</n1:MagnitudeFn>
</n1:CurrencyMeasure>
</n2:currencyType>
<n2:legalSystemType>
<n2:LegalSystemAttribute/>
</n2:legalSystemType>
<n2:primaryGeopoliticalSubdivision>
<n1:GeopoliticalArea>
<n2:JudiciaryFn>
<n1:JudicialOrganization/>
</n2:JudiciaryFn>
<n2:dependentGeopoliticalArea>
<n1:GeopoliticalArea/>
</n2:dependentGeopoliticalArea>
<n2:totalGDP>
<n1:CurrencyMeasure/>
</n2:totalGDP>
<n2:CitizenryFn>
<n1:GroupOfPeople/>
</n2:CitizenryFn>
<n1:GovernmentFn>
<n1:Government/>
</n1:GovernmentFn>
<n2:currencyType>
<n1:CurrencyMeasure/>
</n2:currencyType>
<n2:legalSystemType>
<n2:LegalSystemAttribute/>
</n2:legalSystemType>
<n2:primaryGeopoliticalSubdivision>
<n1:GeopoliticalArea/>
</n2:primaryGeopoliticalSubdivision>
<n2:LegislatureFn>
<n2:LegislativeOrganization/>
</n2:LegislatureFn>
<n2:industryOfArea>
<n1:Physical/>
</n2:industryOfArea>
<n2:climateTypeInArea>
<n2:ClimateZone/>
</n2:climateTypeInArea>
<n2:financialAsset>
<n1:Object/>
</n2:financialAsset>
<n1:leader>
<n1:Human/>
</n1:leader>
<n2:economyType>
<n2:EconomicAttribute/>
</n2:economyType>
<n1:editor>
<n1:Text/>
</n1:editor>
<n1:authors>
<n1:Text/>
</n1:authors>
<n1:WealthFn>
<n1:CurrencyMeasure/>
</n1:WealthFn>
<n1:PropertyFn>
<n1:Set/>
</n1:PropertyFn>
<n2:ExecutiveBranchFn>
<n1:Organization/>
</n2:ExecutiveBranchFn>
<n2:customer>
<n1:Corporation/>
</n2:customer>
<n2:governmentType>
<n2:FormOfGovernment/>
</n2:governmentType>
<n2:leaderPosition>
<n1:Position/>
</n2:leaderPosition>
<n2:fiscalYearPeriod>
<n1:TimeInterval/>
</n2:fiscalYearPeriod>
</n1:GeopoliticalArea>
</n2:primaryGeopoliticalSubdivision>
<n2:LegislatureFn>
<n2:LegislativeOrganization>
<n2:yearOfFounding>
<n1:Integer/>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea/>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization/>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea/>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text/>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent/>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization/>
</n2:ancestorOrganization>
</n2:LegislativeOrganization>
</n2:LegislatureFn>
<n2:industryOfArea>
<n1:Physical>
<n1:hasPurpose>
<n1:Formula/>
</n1:hasPurpose>
<n1:date>
<n1:Day/>
</n1:date>
<n1:WhenFn>
<n1:TimeInterval/>
</n1:WhenFn>
<n1:cooccur>
<n1:Physical/>
</n1:cooccur>
<n1:monetaryValue>
<n1:CurrencyMeasure/>
</n1:monetaryValue>
</n1:Physical>
</n2:industryOfArea>
<n2:climateTypeInArea>
<n2:ClimateZone>
<n2:climateTypeInArea>
<n2:ClimateZone/>
</n2:climateTypeInArea>
</n2:ClimateZone>
</n2:climateTypeInArea>
<n2:financialAsset>
<n1:Object>
<n1:larger>
<n1:Object/>
</n1:larger>
<n2:deviceState>
<n2:DeviceStateAttribute/>
</n2:deviceState>
<n1:faces>
<n1:DirectionalAttribute/>
</n1:faces>
<n2:older>
<n1:Object/>
</n2:older>
<n1:copy>
<n1:Object/>
</n1:copy>
<n1:uses>
<n1:Agent/>
</n1:uses>
<n1:linked>
<n1:Object/>
</n1:linked>
<n1:exploits>
<n1:Agent/>
</n1:exploits>
<n1:fills>
<n1:Hole/>
</n1:fills>
<n2:orbits>
<n1:AstronomicalBody/>
</n2:orbits>
<n2:barometricPressure>
<n2:AtmosphericPressureMeasure/>
</n2:barometricPressure>
<n1:smaller>
<n1:Object/>
</n1:smaller>
<n2:airTemperature>
<n1:TemperatureMeasure/>
</n2:airTemperature>
<n1:hasPurpose>
<n1:Formula/>
</n1:hasPurpose>
<n1:date>
<n1:Day/>
</n1:date>
<n1:WhenFn>
<n1:TimeInterval/>
</n1:WhenFn>
<n1:cooccur>
<n1:Physical/>
</n1:cooccur>
<n1:monetaryValue>
<n1:CurrencyMeasure/>
</n1:monetaryValue>
</n1:Object>
</n2:financialAsset>
<n1:leader>
<n1:Human>
<n2:intelligenceQuotient>
<n1:RationalNumber/>
</n2:intelligenceQuotient>
<n2:grandfather>
<n1:Man/>
</n2:grandfather>
<n1:citizen>
<n1:Nation/>
</n1:citizen>
<n1:ImmediateFamilyFn>
<n1:FamilyGroup/>
</n1:ImmediateFamilyFn>
<n2:birthday>
<n1:Day/>
</n2:birthday>
<n1:home>
<n1:PermanentResidence/>
</n1:home>
<n2:stepmother>
<n1:Woman/>
</n2:stepmother>
<n2:tenant>
<n1:Residence/>
</n2:tenant>
<n2:occupation>
<n1:FinancialTransaction/>
</n2:occupation>
<n2:groupMember>
<n1:GroupOfPeople/>
</n2:groupMember>
<n2:neighbor>
<n1:Human/>
</n2:neighbor>
<n2:DescendantsFn>
<n1:FamilyGroup/>
</n2:DescendantsFn>
<n2:grandmother>
<n1:Man/>
</n2:grandmother>
<n2:stepfather>
<n1:Man/>
</n2:stepfather>
<n2:cousin>
<n1:Human/>
</n2:cousin>
<n1:stays>
<n1:TemporaryResidence/>
</n1:stays>
<n2:patientMedical>
<n1:CognitiveAgent/>
</n2:patientMedical>
<n2:teacher>
<n1:EducationalOrganization/>
</n2:teacher>
<n2:hasExpertise>
<n1:FieldOfStudy/>
</n2:hasExpertise>
<n2:affiliatedOrganization>
<n1:CognitiveAgent/>
</n2:affiliatedOrganization>
<n2:dislikes>
<n1:Object/>
</n2:dislikes>
<n2:enjoys>
<n1:IntentionalProcess/>
</n2:enjoys>
<n2:defendant>
<n1:LegalAction/>
</n2:defendant>
<n2:allegiance>
<n1:CognitiveAgent/>
</n2:allegiance>
<n2:disapproves>
<n1:Formula/>
</n2:disapproves>
<n1:wants>
<n1:Physical/>
</n1:wants>
<n2:plaintiff>
<n1:LegalAction/>
</n2:plaintiff>
<n1:knows>
<n1:Formula/>
</n1:knows>
<n1:desires>
<n1:Formula/>
</n1:desires>
<n2:student>
<n1:EducationalOrganization/>
</n2:student>
<n1:considers>
<n1:Formula/>
</n1:considers>
<n2:doubts>
<n1:Formula/>
</n2:doubts>
</n1:Human>
</n1:leader>
<n2:economyType>
<n2:EconomicAttribute/>
</n2:economyType>
<n1:editor>
<n1:Text>
<n2:registeredItem>
<n1:Physical/>
</n2:registeredItem>
<n1:version>
<n1:Artifact/>
</n1:version>
<n2:equipmentType>
<n1:Device/>
</n2:equipmentType>
<n1:expressedInLanguage>
<n1:Language/>
</n1:expressedInLanguage>
</n1:Text>
</n1:editor>
<n1:authors>
<n1:Text>
<n2:registeredItem>
<n1:Physical/>
</n2:registeredItem>
<n1:version>
<n1:Artifact/>
</n1:version>
<n2:equipmentType>
<n1:Device/>
</n2:equipmentType>
<n1:expressedInLanguage>
<n1:Language/>
</n1:expressedInLanguage>
</n1:Text>
</n1:authors>
<n1:WealthFn>
<n1:CurrencyMeasure>
<n1:MagnitudeFn>
<n1:RealNumber/>
</n1:MagnitudeFn>
</n1:CurrencyMeasure>
</n1:WealthFn>
<n1:PropertyFn>
<n1:Set>
<n1:subset>
<n1:Set/>
</n1:subset>
<n1:ComplementFn>
<n1:SetOrClass/>
</n1:ComplementFn>
<n1:GeneralizedIntersectionFn>
<n1:SetOrClass/>
</n1:GeneralizedIntersectionFn>
<n1:GeneralizedUnionFn>
<n1:SetOrClass/>
</n1:GeneralizedUnionFn>
<n1:disjoint>
<n1:SetOrClass/>
</n1:disjoint>
</n1:Set>
</n1:PropertyFn>
<n2:ExecutiveBranchFn>
<n1:Organization>
<n2:yearOfFounding>
<n1:Integer/>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea/>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization/>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea/>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text/>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent/>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization/>
</n2:ancestorOrganization>
<n2:teacher>
<n1:EducationalOrganization/>
</n2:teacher>
<n2:hasExpertise>
<n1:FieldOfStudy/>
</n2:hasExpertise>
<n2:affiliatedOrganization>
<n1:CognitiveAgent/>
</n2:affiliatedOrganization>
<n2:dislikes>
<n1:Object/>
</n2:dislikes>
<n2:enjoys>
<n1:IntentionalProcess/>
</n2:enjoys>
<n2:defendant>
<n1:LegalAction/>
</n2:defendant>
<n2:allegiance>
<n1:CognitiveAgent/>
</n2:allegiance>
<n2:disapproves>
<n1:Formula/>
</n2:disapproves>
<n1:wants>
<n1:Physical/>
</n1:wants>
<n2:plaintiff>
<n1:LegalAction/>
</n2:plaintiff>
<n1:knows>
<n1:Formula/>
</n1:knows>
<n1:desires>
<n1:Formula/>
</n1:desires>
<n2:student>
<n1:EducationalOrganization/>
</n2:student>
<n1:considers>
<n1:Formula/>
</n1:considers>
<n2:doubts>
<n1:Formula/>
</n2:doubts>
</n1:Organization>
</n2:ExecutiveBranchFn>
<n2:customer>
<n1:Corporation>
<n2:yearOfFounding>
<n1:Integer/>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea/>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization/>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea/>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text/>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent/>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization/>
</n2:ancestorOrganization>
</n1:Corporation>
</n2:customer>
<n2:governmentType>
<n2:FormOfGovernment/>
</n2:governmentType>
<n2:leaderPosition>
<n1:Position/>
</n2:leaderPosition>
<n2:fiscalYearPeriod>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n2:fiscalYearPeriod>
</n1:GeopoliticalArea>
</n2:primaryGeopoliticalSubdivision>
<n2:LegislatureFn>
<n2:LegislativeOrganization>
<n2:yearOfFounding>
<n1:Integer>
<n1:SuccessorFn>
<n1:Integer/>
</n1:SuccessorFn>
<n1:PredecessorFn>
<n1:Integer/>
</n1:PredecessorFn>
<n2:multiplicativeFactor>
<n1:Integer/>
</n2:multiplicativeFactor>
</n1:Integer>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea>
<n2:JudiciaryFn>
<n1:JudicialOrganization/>
</n2:JudiciaryFn>
<n2:dependentGeopoliticalArea>
<n1:GeopoliticalArea/>
</n2:dependentGeopoliticalArea>
<n2:totalGDP>
<n1:CurrencyMeasure/>
</n2:totalGDP>
<n2:CitizenryFn>
<n1:GroupOfPeople/>
</n2:CitizenryFn>
<n1:GovernmentFn>
<n1:Government/>
</n1:GovernmentFn>
<n2:currencyType>
<n1:CurrencyMeasure/>
</n2:currencyType>
<n2:legalSystemType>
<n2:LegalSystemAttribute/>
</n2:legalSystemType>
<n2:primaryGeopoliticalSubdivision>
<n1:GeopoliticalArea/>
</n2:primaryGeopoliticalSubdivision>
<n2:LegislatureFn>
<n2:LegislativeOrganization/>
</n2:LegislatureFn>
<n2:industryOfArea>
<n1:Physical/>
</n2:industryOfArea>
<n2:climateTypeInArea>
<n2:ClimateZone/>
</n2:climateTypeInArea>
<n2:financialAsset>
<n1:Object/>
</n2:financialAsset>
<n1:leader>
<n1:Human/>
</n1:leader>
<n2:economyType>
<n2:EconomicAttribute/>
</n2:economyType>
<n1:editor>
<n1:Text/>
</n1:editor>
<n1:authors>
<n1:Text/>
</n1:authors>
<n1:WealthFn>
<n1:CurrencyMeasure/>
</n1:WealthFn>
<n1:PropertyFn>
<n1:Set/>
</n1:PropertyFn>
<n2:ExecutiveBranchFn>
<n1:Organization/>
</n2:ExecutiveBranchFn>
<n2:customer>
<n1:Corporation/>
</n2:customer>
<n2:governmentType>
<n2:FormOfGovernment/>
</n2:governmentType>
<n2:leaderPosition>
<n1:Position/>
</n2:leaderPosition>
<n2:fiscalYearPeriod>
<n1:TimeInterval/>
</n2:fiscalYearPeriod>
</n1:GeopoliticalArea>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization>
<n2:yearOfFounding>
<n1:Integer/>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea/>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization/>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea/>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text/>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent/>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization/>
</n2:ancestorOrganization>
<n2:teacher>
<n1:EducationalOrganization/>
</n2:teacher>
<n2:hasExpertise>
<n1:FieldOfStudy/>
</n2:hasExpertise>
<n2:affiliatedOrganization>
<n1:CognitiveAgent/>
</n2:affiliatedOrganization>
<n2:dislikes>
<n1:Object/>
</n2:dislikes>
<n2:enjoys>
<n1:IntentionalProcess/>
</n2:enjoys>
<n2:defendant>
<n1:LegalAction/>
</n2:defendant>
<n2:allegiance>
<n1:CognitiveAgent/>
</n2:allegiance>
<n2:disapproves>
<n1:Formula/>
</n2:disapproves>
<n1:wants>
<n1:Physical/>
</n1:wants>
<n2:plaintiff>
<n1:LegalAction/>
</n2:plaintiff>
<n1:knows>
<n1:Formula/>
</n1:knows>
<n1:desires>
<n1:Formula/>
</n1:desires>
<n2:student>
<n1:EducationalOrganization/>
</n2:student>
<n1:considers>
<n1:Formula/>
</n1:considers>
<n2:doubts>
<n1:Formula/>
</n2:doubts>
</n1:Organization>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea>
<n2:JudiciaryFn>
<n1:JudicialOrganization/>
</n2:JudiciaryFn>
<n2:dependentGeopoliticalArea>
<n1:GeopoliticalArea/>
</n2:dependentGeopoliticalArea>
<n2:totalGDP>
<n1:CurrencyMeasure/>
</n2:totalGDP>
<n2:CitizenryFn>
<n1:GroupOfPeople/>
</n2:CitizenryFn>
<n1:GovernmentFn>
<n1:Government/>
</n1:GovernmentFn>
<n2:currencyType>
<n1:CurrencyMeasure/>
</n2:currencyType>
<n2:legalSystemType>
<n2:LegalSystemAttribute/>
</n2:legalSystemType>
<n2:primaryGeopoliticalSubdivision>
<n1:GeopoliticalArea/>
</n2:primaryGeopoliticalSubdivision>
<n2:LegislatureFn>
<n2:LegislativeOrganization/>
</n2:LegislatureFn>
<n2:industryOfArea>
<n1:Physical/>
</n2:industryOfArea>
<n2:climateTypeInArea>
<n2:ClimateZone/>
</n2:climateTypeInArea>
<n2:financialAsset>
<n1:Object/>
</n2:financialAsset>
<n1:leader>
<n1:Human/>
</n1:leader>
<n2:economyType>
<n2:EconomicAttribute/>
</n2:economyType>
<n1:editor>
<n1:Text/>
</n1:editor>
<n1:authors>
<n1:Text/>
</n1:authors>
<n1:WealthFn>
<n1:CurrencyMeasure/>
</n1:WealthFn>
<n1:PropertyFn>
<n1:Set/>
</n1:PropertyFn>
<n2:ExecutiveBranchFn>
<n1:Organization/>
</n2:ExecutiveBranchFn>
<n2:customer>
<n1:Corporation/>
</n2:customer>
<n2:governmentType>
<n2:FormOfGovernment/>
</n2:governmentType>
<n2:leaderPosition>
<n1:Position/>
</n2:leaderPosition>
<n2:fiscalYearPeriod>
<n1:TimeInterval/>
</n2:fiscalYearPeriod>
</n1:GeopoliticalArea>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text>
<n2:registeredItem>
<n1:Physical/>
</n2:registeredItem>
<n1:version>
<n1:Artifact/>
</n1:version>
<n2:equipmentType>
<n1:Device/>
</n2:equipmentType>
<n1:expressedInLanguage>
<n1:Language/>
</n1:expressedInLanguage>
</n1:Text>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent>
<n2:teacher>
<n1:EducationalOrganization/>
</n2:teacher>
<n2:hasExpertise>
<n1:FieldOfStudy/>
</n2:hasExpertise>
<n2:affiliatedOrganization>
<n1:CognitiveAgent/>
</n2:affiliatedOrganization>
<n2:dislikes>
<n1:Object/>
</n2:dislikes>
<n2:enjoys>
<n1:IntentionalProcess/>
</n2:enjoys>
<n2:defendant>
<n1:LegalAction/>
</n2:defendant>
<n2:allegiance>
<n1:CognitiveAgent/>
</n2:allegiance>
<n2:disapproves>
<n1:Formula/>
</n2:disapproves>
<n1:wants>
<n1:Physical/>
</n1:wants>
<n2:plaintiff>
<n1:LegalAction/>
</n2:plaintiff>
<n1:knows>
<n1:Formula/>
</n1:knows>
<n1:desires>
<n1:Formula/>
</n1:desires>
<n2:student>
<n1:EducationalOrganization/>
</n2:student>
<n1:considers>
<n1:Formula/>
</n1:considers>
<n2:doubts>
<n1:Formula/>
</n2:doubts>
<n2:speaksLanguage>
<n1:Language/>
</n2:speaksLanguage>
</n1:CognitiveAgent>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization>
<n2:yearOfFounding>
<n1:Integer/>
</n2:yearOfFounding>
<n2:religiousAffiliationOfOrganization>
<n1:BeliefGroup/>
</n2:religiousAffiliationOfOrganization>
<n2:agentOperatesInArea>
<n1:GeopoliticalArea/>
</n2:agentOperatesInArea>
<n1:subOrganization>
<n1:Organization/>
</n1:subOrganization>
<n2:ideologicalAffiliationOfOrganization>
<n2:FormOfGovernment/>
</n2:ideologicalAffiliationOfOrganization>
<n2:headquartersOfOrganization>
<n1:GeopoliticalArea/>
</n2:headquartersOfOrganization>
<n1:publishes>
<n1:Text/>
</n1:publishes>
<n1:employs>
<n1:CognitiveAgent/>
</n1:employs>
<n2:ancestorOrganization>
<n1:Organization/>
</n2:ancestorOrganization>
<n2:teacher>
<n1:EducationalOrganization/>
</n2:teacher>
<n2:hasExpertise>
<n1:FieldOfStudy/>
</n2:hasExpertise>
<n2:affiliatedOrganization>
<n1:CognitiveAgent/>
</n2:affiliatedOrganization>
<n2:dislikes>
<n1:Object/>
</n2:dislikes>
<n2:enjoys>
<n1:IntentionalProcess/>
</n2:enjoys>
<n2:defendant>
<n1:LegalAction/>
</n2:defendant>
<n2:allegiance>
<n1:CognitiveAgent/>
</n2:allegiance>
<n2:disapproves>
<n1:Formula/>
</n2:disapproves>
<n1:wants>
<n1:Physical/>
</n1:wants>
<n2:plaintiff>
<n1:LegalAction/>
</n2:plaintiff>
<n1:knows>
<n1:Formula/>
</n1:knows>
<n1:desires>
<n1:Formula/>
</n1:desires>
<n2:student>
<n1:EducationalOrganization/>
</n2:student>
<n1:considers>
<n1:Formula/>
</n1:considers>
<n2:doubts>
<n1:Formula/>
</n2:doubts>
</n1:Organization>
</n2:ancestorOrganization>
</n2:LegislativeOrganization>
</n2:LegislatureFn>
<n2:industryOfArea>
<n1:Physical>
<n1:hasPurpose>
<n1:Formula>
<n1:ProbabilityFn>
<n1:RealNumber/>
</n1:ProbabilityFn>
<n1:decreasesLikelihood>
<n1:Formula/>
</n1:decreasesLikelihood>
<n1:independentProbability>
<n1:Formula/>
</n1:independentProbability>
<n1:increasesLikelihood>
<n1:Formula/>
</n1:increasesLikelihood>
<n1:modalAttribute>
<n1:NormativeAttribute/>
</n1:modalAttribute>
<n1:entails>
<n1:Formula/>
</n1:entails>
<n1:true>
<n1:TruthValue/>
</n1:true>
</n1:Formula>
</n1:hasPurpose>
<n1:date>
<n1:Day>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
</n1:Day>
</n1:date>
<n1:WhenFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:WhenFn>
<n1:cooccur>
<n1:Physical>
<n1:hasPurpose>
<n1:Formula/>
</n1:hasPurpose>
<n1:date>
<n1:Day/>
</n1:date>
<n1:WhenFn>
<n1:TimeInterval/>
</n1:WhenFn>
<n1:cooccur>
<n1:Physical/>
</n1:cooccur>
<n1:monetaryValue>
<n1:CurrencyMeasure/>
</n1:monetaryValue>
</n1:Physical>
</n1:cooccur>
<n1:monetaryValue>
<n1:CurrencyMeasure>
<n1:MagnitudeFn>
<n1:RealNumber/>
</n1:MagnitudeFn>
</n1:CurrencyMeasure>
</n1:monetaryValue>
</n1:Physical>
</n2:industryOfArea>
</n1:City>
</rdf:RDF>
</xsl:template>
</xsl:transform>
