<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:n1="http://127.0.0.1:8000/ontology/SUMO.owl#" xmlns:n2="http://127.0.0.1:8000/ontology/Mid-level-ontology.owl#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:service="http://127.0.0.1:8000/services/OWLS-1.1/country_professiontimemeasure_service.owls" version="2.0">
<xsl:output encoding="iso-8859-1" indent="yes" method="xml" version="1.0"/>
<xsl:template match="/">
<rdf:RDF>
<n1:TimeMeasure>
<n1:MagnitudeFn>
<n1:RealNumber>
<n1:CeilingFn>
<n1:Integer>
<n1:SuccessorFn>
<n1:Integer/>
</n1:SuccessorFn>
<n1:PredecessorFn>
<n1:Integer/>
</n1:PredecessorFn>
<n2:multiplicativeFactor>
<n1:Integer/>
</n2:multiplicativeFactor>
</n1:Integer>
</n1:CeilingFn>
<n1:IntegerSquareRootFn>
<n1:NonnegativeInteger>
<n1:SuccessorFn>
<n1:Integer/>
</n1:SuccessorFn>
<n1:PredecessorFn>
<n1:Integer/>
</n1:PredecessorFn>
<n2:multiplicativeFactor>
<n1:Integer/>
</n2:multiplicativeFactor>
</n1:NonnegativeInteger>
</n1:IntegerSquareRootFn>
<n1:FloorFn>
<n1:Integer>
<n1:SuccessorFn>
<n1:Integer/>
</n1:SuccessorFn>
<n1:PredecessorFn>
<n1:Integer/>
</n1:PredecessorFn>
<n2:multiplicativeFactor>
<n1:Integer/>
</n2:multiplicativeFactor>
</n1:Integer>
</n1:FloorFn>
<n1:SignumFn>
<n1:Integer>
<n1:SuccessorFn>
<n1:Integer/>
</n1:SuccessorFn>
<n1:PredecessorFn>
<n1:Integer/>
</n1:PredecessorFn>
<n2:multiplicativeFactor>
<n1:Integer/>
</n2:multiplicativeFactor>
</n1:Integer>
</n1:SignumFn>
<n1:NumeratorFn>
<n1:Integer>
<n1:SuccessorFn>
<n1:Integer/>
</n1:SuccessorFn>
<n1:PredecessorFn>
<n1:Integer/>
</n1:PredecessorFn>
<n2:multiplicativeFactor>
<n1:Integer/>
</n2:multiplicativeFactor>
</n1:Integer>
</n1:NumeratorFn>
<n1:SquareRootFn>
<n1:Number>
<n1:RealNumberFn>
<n1:RealNumber/>
</n1:RealNumberFn>
<n1:RationalNumberFn>
<n1:RationalNumber/>
</n1:RationalNumberFn>
<n1:lessThanOrEqualTo>
<n1:Quantity/>
</n1:lessThanOrEqualTo>
<n1:lessThan>
<n1:Quantity/>
</n1:lessThan>
<n1:greaterThanOrEqualTo>
<n1:Quantity/>
</n1:greaterThanOrEqualTo>
<n1:ReciprocalFn>
<n1:Quantity/>
</n1:ReciprocalFn>
<n1:greaterThan>
<n1:Quantity/>
</n1:greaterThan>
<n1:RoundFn>
<n1:Quantity/>
</n1:RoundFn>
</n1:Number>
</n1:SquareRootFn>
<n1:AbsoluteValueFn>
<n1:NonnegativeRealNumber>
<n1:CeilingFn>
<n1:Integer/>
</n1:CeilingFn>
<n1:IntegerSquareRootFn>
<n1:NonnegativeInteger/>
</n1:IntegerSquareRootFn>
<n1:FloorFn>
<n1:Integer/>
</n1:FloorFn>
<n1:SignumFn>
<n1:Integer/>
</n1:SignumFn>
<n1:NumeratorFn>
<n1:Integer/>
</n1:NumeratorFn>
<n1:SquareRootFn>
<n1:Number/>
</n1:SquareRootFn>
<n1:AbsoluteValueFn>
<n1:NonnegativeRealNumber/>
</n1:AbsoluteValueFn>
<n1:DenominatorFn>
<n1:Integer/>
</n1:DenominatorFn>
</n1:NonnegativeRealNumber>
</n1:AbsoluteValueFn>
<n1:DenominatorFn>
<n1:Integer>
<n1:SuccessorFn>
<n1:Integer/>
</n1:SuccessorFn>
<n1:PredecessorFn>
<n1:Integer/>
</n1:PredecessorFn>
<n2:multiplicativeFactor>
<n1:Integer/>
</n2:multiplicativeFactor>
</n1:Integer>
</n1:DenominatorFn>
<n1:RealNumberFn>
<n1:RealNumber>
<n1:CeilingFn>
<n1:Integer/>
</n1:CeilingFn>
<n1:IntegerSquareRootFn>
<n1:NonnegativeInteger/>
</n1:IntegerSquareRootFn>
<n1:FloorFn>
<n1:Integer/>
</n1:FloorFn>
<n1:SignumFn>
<n1:Integer/>
</n1:SignumFn>
<n1:NumeratorFn>
<n1:Integer/>
</n1:NumeratorFn>
<n1:SquareRootFn>
<n1:Number/>
</n1:SquareRootFn>
<n1:AbsoluteValueFn>
<n1:NonnegativeRealNumber/>
</n1:AbsoluteValueFn>
<n1:DenominatorFn>
<n1:Integer/>
</n1:DenominatorFn>
<n1:RealNumberFn>
<n1:RealNumber/>
</n1:RealNumberFn>
<n1:RationalNumberFn>
<n1:RationalNumber/>
</n1:RationalNumberFn>
</n1:RealNumber>
</n1:RealNumberFn>
<n1:RationalNumberFn>
<n1:RationalNumber>
<n1:CeilingFn>
<n1:Integer/>
</n1:CeilingFn>
<n1:IntegerSquareRootFn>
<n1:NonnegativeInteger/>
</n1:IntegerSquareRootFn>
<n1:FloorFn>
<n1:Integer/>
</n1:FloorFn>
<n1:SignumFn>
<n1:Integer/>
</n1:SignumFn>
<n1:NumeratorFn>
<n1:Integer/>
</n1:NumeratorFn>
<n1:SquareRootFn>
<n1:Number/>
</n1:SquareRootFn>
<n1:AbsoluteValueFn>
<n1:NonnegativeRealNumber/>
</n1:AbsoluteValueFn>
<n1:DenominatorFn>
<n1:Integer/>
</n1:DenominatorFn>
</n1:RationalNumber>
</n1:RationalNumberFn>
</n1:RealNumber>
</n1:MagnitudeFn>
</n1:TimeMeasure>
</rdf:RDF>
</xsl:template>
</xsl:transform>
