<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:n1="http://127.0.0.1:8000/ontology/SUMO.owl#" xmlns:n2="http://127.0.0.1:8000/ontology/Mid-level-ontology.owl#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:service="http://127.0.0.1:8000/services/OWLS-1.1/grocerystore_butterselling_service.owls" version="2.0">
<xsl:output encoding="iso-8859-1" indent="yes" method="xml" version="1.0"/>
<xsl:template match="/">
<rdf:RDF>
<n1:Selling>
<n1:transactionAmount>
<n1:CurrencyMeasure>
<n1:MagnitudeFn>
<n1:RealNumber>
<n1:CeilingFn>
<n1:Integer/>
</n1:CeilingFn>
<n1:IntegerSquareRootFn>
<n1:NonnegativeInteger/>
</n1:IntegerSquareRootFn>
<n1:FloorFn>
<n1:Integer/>
</n1:FloorFn>
<n1:SignumFn>
<n1:Integer/>
</n1:SignumFn>
<n1:NumeratorFn>
<n1:Integer/>
</n1:NumeratorFn>
<n1:SquareRootFn>
<n1:Number/>
</n1:SquareRootFn>
<n1:AbsoluteValueFn>
<n1:NonnegativeRealNumber/>
</n1:AbsoluteValueFn>
<n1:DenominatorFn>
<n1:Integer/>
</n1:DenominatorFn>
<n1:RealNumberFn>
<n1:RealNumber/>
</n1:RealNumberFn>
<n1:RationalNumberFn>
<n1:RationalNumber/>
</n1:RationalNumberFn>
</n1:RealNumber>
</n1:MagnitudeFn>
</n1:CurrencyMeasure>
</n1:transactionAmount>
<n2:loss>
<n1:CurrencyMeasure>
<n1:MagnitudeFn>
<n1:RealNumber>
<n1:CeilingFn>
<n1:Integer/>
</n1:CeilingFn>
<n1:IntegerSquareRootFn>
<n1:NonnegativeInteger/>
</n1:IntegerSquareRootFn>
<n1:FloorFn>
<n1:Integer/>
</n1:FloorFn>
<n1:SignumFn>
<n1:Integer/>
</n1:SignumFn>
<n1:NumeratorFn>
<n1:Integer/>
</n1:NumeratorFn>
<n1:SquareRootFn>
<n1:Number/>
</n1:SquareRootFn>
<n1:AbsoluteValueFn>
<n1:NonnegativeRealNumber/>
</n1:AbsoluteValueFn>
<n1:DenominatorFn>
<n1:Integer/>
</n1:DenominatorFn>
<n1:RealNumberFn>
<n1:RealNumber/>
</n1:RealNumberFn>
<n1:RationalNumberFn>
<n1:RationalNumber/>
</n1:RationalNumberFn>
</n1:RealNumber>
</n1:MagnitudeFn>
</n1:CurrencyMeasure>
</n2:loss>
<n2:profit>
<n1:CurrencyMeasure>
<n1:MagnitudeFn>
<n1:RealNumber>
<n1:CeilingFn>
<n1:Integer/>
</n1:CeilingFn>
<n1:IntegerSquareRootFn>
<n1:NonnegativeInteger/>
</n1:IntegerSquareRootFn>
<n1:FloorFn>
<n1:Integer/>
</n1:FloorFn>
<n1:SignumFn>
<n1:Integer/>
</n1:SignumFn>
<n1:NumeratorFn>
<n1:Integer/>
</n1:NumeratorFn>
<n1:SquareRootFn>
<n1:Number/>
</n1:SquareRootFn>
<n1:AbsoluteValueFn>
<n1:NonnegativeRealNumber/>
</n1:AbsoluteValueFn>
<n1:DenominatorFn>
<n1:Integer/>
</n1:DenominatorFn>
<n1:RealNumberFn>
<n1:RealNumber/>
</n1:RealNumberFn>
<n1:RationalNumberFn>
<n1:RationalNumber/>
</n1:RationalNumberFn>
</n1:RealNumber>
</n1:MagnitudeFn>
</n1:CurrencyMeasure>
</n2:profit>
</n1:Selling>
</rdf:RDF>
</xsl:template>
</xsl:transform>
