<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:n1="http://127.0.0.1:8000/ontology/SUMO.owl#" xmlnshttp://127.0.0.1:8000/ontology/logy/Mid-level-ontology.owl#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:service="http://127.0.0.1:8000/services/OWLS-1.1/municipal-unit_weatherprocess_service.owls" version="2.0">
<xsl:output encoding="iso-8859-1" indent="yes" method="xml" version="1.0"/>
<xsl:template match="/">
<rdf:RDF>
<n1:WeatherProcess>
<n1:path>
<n1:Object>
<n1:larger>
<n1:Object>
<n1:larger>
<n1:Object/>
</n1:larger>
<n2:deviceState>
<n2:DeviceStateAttribute/>
</n2:deviceState>
<n1:faces>
<n1:DirectionalAttribute/>
</n1:faces>
<n2:older>
<n1:Object/>
</n2:older>
<n1:copy>
<n1:Object/>
</n1:copy>
<n1:uses>
<n1:Agent/>
</n1:uses>
<n1:linked>
<n1:Object/>
</n1:linked>
<n1:exploits>
<n1:Agent/>
</n1:exploits>
<n1:fills>
<n1:Hole/>
</n1:fills>
<n2:orbits>
<n1:AstronomicalBody/>
</n2:orbits>
<n2:barometricPressure>
<n2:AtmosphericPressureMeasure/>
</n2:barometricPressure>
<n1:smaller>
<n1:Object/>
</n1:smaller>
<n2:airTemperature>
<n1:TemperatureMeasure/>
</n2:airTemperature>
<n1:hasPurpose>
<n1:Formula/>
</n1:hasPurpose>
<n1:date>
<n1:Day/>
</n1:date>
<n1:WhenFn>
<n1:TimeInterval/>
</n1:WhenFn>
<n1:cooccur>
<n1:Physical/>
</n1:cooccur>
<n1:monetaryValue>
<n1:CurrencyMeasure/>
</n1:monetaryValue>
</n1:Object>
</n1:larger>
<n2:deviceState>
<n2:DeviceStateAttribute/>
</n2:deviceState>
<n1:faces>
<n1:DirectionalAttribute/>
</n1:faces>
<n2:older>
<n1:Object>
<n1:larger>
<n1:Object/>
</n1:larger>
<n2:deviceState>
<n2:DeviceStateAttribute/>
</n2:deviceState>
<n1:faces>
<n1:DirectionalAttribute/>
</n1:faces>
<n2:older>
<n1:Object/>
</n2:older>
<n1:copy>
<n1:Object/>
</n1:copy>
<n1:uses>
<n1:Agent/>
</n1:uses>
<n1:linked>
<n1:Object/>
</n1:linked>
<n1:exploits>
<n1:Agent/>
</n1:exploits>
<n1:fills>
<n1:Hole/>
</n1:fills>
<n2:orbits>
<n1:AstronomicalBody/>
</n2:orbits>
<n2:barometricPressure>
<n2:AtmosphericPressureMeasure/>
</n2:barometricPressure>
<n1:smaller>
<n1:Object/>
</n1:smaller>
<n2:airTemperature>
<n1:TemperatureMeasure/>
</n2:airTemperature>
<n1:hasPurpose>
<n1:Formula/>
</n1:hasPurpose>
<n1:date>
<n1:Day/>
</n1:date>
<n1:WhenFn>
<n1:TimeInterval/>
</n1:WhenFn>
<n1:cooccur>
<n1:Physical/>
</n1:cooccur>
<n1:monetaryValue>
<n1:CurrencyMeasure/>
</n1:monetaryValue>
</n1:Object>
</n2:older>
<n1:copy>
<n1:Object>
<n1:larger>
<n1:Object/>
</n1:larger>
<n2:deviceState>
<n2:DeviceStateAttribute/>
</n2:deviceState>
<n1:faces>
<n1:DirectionalAttribute/>
</n1:faces>
<n2:older>
<n1:Object/>
</n2:older>
<n1:copy>
<n1:Object/>
</n1:copy>
<n1:uses>
<n1:Agent/>
</n1:uses>
<n1:linked>
<n1:Object/>
</n1:linked>
<n1:exploits>
<n1:Agent/>
</n1:exploits>
<n1:fills>
<n1:Hole/>
</n1:fills>
<n2:orbits>
<n1:AstronomicalBody/>
</n2:orbits>
<n2:barometricPressure>
<n2:AtmosphericPressureMeasure/>
</n2:barometricPressure>
<n1:smaller>
<n1:Object/>
</n1:smaller>
<n2:airTemperature>
<n1:TemperatureMeasure/>
</n2:airTemperature>
<n1:hasPurpose>
<n1:Formula/>
</n1:hasPurpose>
<n1:date>
<n1:Day/>
</n1:date>
<n1:WhenFn>
<n1:TimeInterval/>
</n1:WhenFn>
<n1:cooccur>
<n1:Physical/>
</n1:cooccur>
<n1:monetaryValue>
<n1:CurrencyMeasure/>
</n1:monetaryValue>
</n1:Object>
</n1:copy>
<n1:uses>
<n1:Agent>
<n2:financialAsset>
<n1:Object/>
</n2:financialAsset>
<n1:leader>
<n1:Human/>
</n1:leader>
<n2:economyType>
<n2:EconomicAttribute/>
</n2:economyType>
<n1:editor>
<n1:Text/>
</n1:editor>
<n1:authors>
<n1:Text/>
</n1:authors>
<n1:WealthFn>
<n1:CurrencyMeasure/>
</n1:WealthFn>
<n1:PropertyFn>
<n1:Set/>
</n1:PropertyFn>
<n2:ExecutiveBranchFn>
<n1:Organization/>
</n2:ExecutiveBranchFn>
<n2:customer>
<n1:Corporation/>
</n2:customer>
<n2:governmentType>
<n2:FormOfGovernment/>
</n2:governmentType>
<n2:leaderPosition>
<n1:Position/>
</n2:leaderPosition>
<n2:fiscalYearPeriod>
<n1:TimeInterval/>
</n2:fiscalYearPeriod>
<n1:larger>
<n1:Object/>
</n1:larger>
<n2:deviceState>
<n2:DeviceStateAttribute/>
</n2:deviceState>
<n1:faces>
<n1:DirectionalAttribute/>
</n1:faces>
<n2:older>
<n1:Object/>
</n2:older>
<n1:copy>
<n1:Object/>
</n1:copy>
<n1:uses>
<n1:Agent/>
</n1:uses>
<n1:linked>
<n1:Object/>
</n1:linked>
<n1:exploits>
<n1:Agent/>
</n1:exploits>
<n1:fills>
<n1:Hole/>
</n1:fills>
<n2:orbits>
<n1:AstronomicalBody/>
</n2:orbits>
<n2:barometricPressure>
<n2:AtmosphericPressureMeasure/>
</n2:barometricPressure>
<n1:smaller>
<n1:Object/>
</n1:smaller>
<n2:airTemperature>
<n1:TemperatureMeasure/>
</n2:airTemperature>
</n1:Agent>
</n1:uses>
<n1:linked>
<n1:Object>
<n1:larger>
<n1:Object/>
</n1:larger>
<n2:deviceState>
<n2:DeviceStateAttribute/>
</n2:deviceState>
<n1:faces>
<n1:DirectionalAttribute/>
</n1:faces>
<n2:older>
<n1:Object/>
</n2:older>
<n1:copy>
<n1:Object/>
</n1:copy>
<n1:uses>
<n1:Agent/>
</n1:uses>
<n1:linked>
<n1:Object/>
</n1:linked>
<n1:exploits>
<n1:Agent/>
</n1:exploits>
<n1:fills>
<n1:Hole/>
</n1:fills>
<n2:orbits>
<n1:AstronomicalBody/>
</n2:orbits>
<n2:barometricPressure>
<n2:AtmosphericPressureMeasure/>
</n2:barometricPressure>
<n1:smaller>
<n1:Object/>
</n1:smaller>
<n2:airTemperature>
<n1:TemperatureMeasure/>
</n2:airTemperature>
<n1:hasPurpose>
<n1:Formula/>
</n1:hasPurpose>
<n1:date>
<n1:Day/>
</n1:date>
<n1:WhenFn>
<n1:TimeInterval/>
</n1:WhenFn>
<n1:cooccur>
<n1:Physical/>
</n1:cooccur>
<n1:monetaryValue>
<n1:CurrencyMeasure/>
</n1:monetaryValue>
</n1:Object>
</n1:linked>
<n1:exploits>
<n1:Agent>
<n2:financialAsset>
<n1:Object/>
</n2:financialAsset>
<n1:leader>
<n1:Human/>
</n1:leader>
<n2:economyType>
<n2:EconomicAttribute/>
</n2:economyType>
<n1:editor>
<n1:Text/>
</n1:editor>
<n1:authors>
<n1:Text/>
</n1:authors>
<n1:WealthFn>
<n1:CurrencyMeasure/>
</n1:WealthFn>
<n1:PropertyFn>
<n1:Set/>
</n1:PropertyFn>
<n2:ExecutiveBranchFn>
<n1:Organization/>
</n2:ExecutiveBranchFn>
<n2:customer>
<n1:Corporation/>
</n2:customer>
<n2:governmentType>
<n2:FormOfGovernment/>
</n2:governmentType>
<n2:leaderPosition>
<n1:Position/>
</n2:leaderPosition>
<n2:fiscalYearPeriod>
<n1:TimeInterval/>
</n2:fiscalYearPeriod>
<n1:larger>
<n1:Object/>
</n1:larger>
<n2:deviceState>
<n2:DeviceStateAttribute/>
</n2:deviceState>
<n1:faces>
<n1:DirectionalAttribute/>
</n1:faces>
<n2:older>
<n1:Object/>
</n2:older>
<n1:copy>
<n1:Object/>
</n1:copy>
<n1:uses>
<n1:Agent/>
</n1:uses>
<n1:linked>
<n1:Object/>
</n1:linked>
<n1:exploits>
<n1:Agent/>
</n1:exploits>
<n1:fills>
<n1:Hole/>
</n1:fills>
<n2:orbits>
<n1:AstronomicalBody/>
</n2:orbits>
<n2:barometricPressure>
<n2:AtmosphericPressureMeasure/>
</n2:barometricPressure>
<n1:smaller>
<n1:Object/>
</n1:smaller>
<n2:airTemperature>
<n1:TemperatureMeasure/>
</n2:airTemperature>
</n1:Agent>
</n1:exploits>
<n1:fills>
<n1:Hole>
<n1:HoleSkinFn>
<n1:Object/>
</n1:HoleSkinFn>
<n1:hole>
<n1:SelfConnectedObject/>
</n1:hole>
<n1:HoleHostFn>
<n1:Object/>
</n1:HoleHostFn>
<n2:subRegion>
<n1:Region/>
</n2:subRegion>
</n1:Hole>
</n1:fills>
<n2:orbits>
<n1:AstronomicalBody>
<n2:subRegion>
<n1:Region/>
</n2:subRegion>
</n1:AstronomicalBody>
</n2:orbits>
<n2:barometricPressure>
<n2:AtmosphericPressureMeasure>
<n1:MagnitudeFn>
<n1:RealNumber/>
</n1:MagnitudeFn>
</n2:AtmosphericPressureMeasure>
</n2:barometricPressure>
<n1:smaller>
<n1:Object>
<n1:larger>
<n1:Object/>
</n1:larger>
<n2:deviceState>
<n2:DeviceStateAttribute/>
</n2:deviceState>
<n1:faces>
<n1:DirectionalAttribute/>
</n1:faces>
<n2:older>
<n1:Object/>
</n2:older>
<n1:copy>
<n1:Object/>
</n1:copy>
<n1:uses>
<n1:Agent/>
</n1:uses>
<n1:linked>
<n1:Object/>
</n1:linked>
<n1:exploits>
<n1:Agent/>
</n1:exploits>
<n1:fills>
<n1:Hole/>
</n1:fills>
<n2:orbits>
<n1:AstronomicalBody/>
</n2:orbits>
<n2:barometricPressure>
<n2:AtmosphericPressureMeasure/>
</n2:barometricPressure>
<n1:smaller>
<n1:Object/>
</n1:smaller>
<n2:airTemperature>
<n1:TemperatureMeasure/>
</n2:airTemperature>
<n1:hasPurpose>
<n1:Formula/>
</n1:hasPurpose>
<n1:date>
<n1:Day/>
</n1:date>
<n1:WhenFn>
<n1:TimeInterval/>
</n1:WhenFn>
<n1:cooccur>
<n1:Physical/>
</n1:cooccur>
<n1:monetaryValue>
<n1:CurrencyMeasure/>
</n1:monetaryValue>
</n1:Object>
</n1:smaller>
<n2:airTemperature>
<n1:TemperatureMeasure>
<n1:MagnitudeFn>
<n1:RealNumber/>
</n1:MagnitudeFn>
</n1:TemperatureMeasure>
</n2:airTemperature>
<n1:hasPurpose>
<n1:Formula>
<n1:ProbabilityFn>
<n1:RealNumber/>
</n1:ProbabilityFn>
<n1:decreasesLikelihood>
<n1:Formula/>
</n1:decreasesLikelihood>
<n1:independentProbability>
<n1:Formula/>
</n1:independentProbability>
<n1:increasesLikelihood>
<n1:Formula/>
</n1:increasesLikelihood>
<n1:modalAttribute>
<n1:NormativeAttribute/>
</n1:modalAttribute>
<n1:entails>
<n1:Formula/>
</n1:entails>
<n1:true>
<n1:TruthValue/>
</n1:true>
</n1:Formula>
</n1:hasPurpose>
<n1:date>
<n1:Day>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
</n1:Day>
</n1:date>
<n1:WhenFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:WhenFn>
<n1:cooccur>
<n1:Physical>
<n1:hasPurpose>
<n1:Formula/>
</n1:hasPurpose>
<n1:date>
<n1:Day/>
</n1:date>
<n1:WhenFn>
<n1:TimeInterval/>
</n1:WhenFn>
<n1:cooccur>
<n1:Physical/>
</n1:cooccur>
<n1:monetaryValue>
<n1:CurrencyMeasure/>
</n1:monetaryValue>
</n1:Physical>
</n1:cooccur>
<n1:monetaryValue>
<n1:CurrencyMeasure>
<n1:MagnitudeFn>
<n1:RealNumber/>
</n1:MagnitudeFn>
</n1:CurrencyMeasure>
</n1:monetaryValue>
</n1:Object>
</n1:path>
</n1:WeatherProcess>
</rdf:RDF>
</xsl:template>
</xsl:transform>
