<xsl:transform xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:n1="http://127.0.0.1:8000/ontology/SUMO.owl#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:service="http://127.0.0.1:8000/services/OWLS-1.1/Renaultyear_recommendedpriceineuro_service.owls" version="2.0">
<xsl:output encoding="iso-8859-1" indent="yes" method="xml" version="1.0"/>
<xsl:template match="/">
<rdf:RDF>
<n1:Year>
<n1:starts>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:starts>
<n1:finishes>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint>
<n1:before>
<n1:TimePoint/>
</n1:before>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimePoint>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:during>
<n1:EndFn>
<n1:TimePoint>
<n1:before>
<n1:TimePoint/>
</n1:before>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimePoint>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula>
<n1:ProbabilityFn>
<n1:RealNumber/>
</n1:ProbabilityFn>
<n1:decreasesLikelihood>
<n1:Formula/>
</n1:decreasesLikelihood>
<n1:independentProbability>
<n1:Formula/>
</n1:independentProbability>
<n1:increasesLikelihood>
<n1:Formula/>
</n1:increasesLikelihood>
<n1:modalAttribute>
<n1:NormativeAttribute/>
</n1:modalAttribute>
<n1:entails>
<n1:Formula/>
</n1:entails>
<n1:true>
<n1:TruthValue/>
</n1:true>
</n1:Formula>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:starts>
<n1:finishes>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:starts>
<n1:finishes>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint>
<n1:before>
<n1:TimePoint/>
</n1:before>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimePoint>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:during>
<n1:EndFn>
<n1:TimePoint>
<n1:before>
<n1:TimePoint/>
</n1:before>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimePoint>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula>
<n1:ProbabilityFn>
<n1:RealNumber/>
</n1:ProbabilityFn>
<n1:decreasesLikelihood>
<n1:Formula/>
</n1:decreasesLikelihood>
<n1:independentProbability>
<n1:Formula/>
</n1:independentProbability>
<n1:increasesLikelihood>
<n1:Formula/>
</n1:increasesLikelihood>
<n1:modalAttribute>
<n1:NormativeAttribute/>
</n1:modalAttribute>
<n1:entails>
<n1:Formula/>
</n1:entails>
<n1:true>
<n1:TruthValue/>
</n1:true>
</n1:Formula>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint>
<n1:before>
<n1:TimePoint>
<n1:before>
<n1:TimePoint/>
</n1:before>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimePoint>
</n1:before>
<n1:FutureFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula>
<n1:ProbabilityFn>
<n1:RealNumber/>
</n1:ProbabilityFn>
<n1:decreasesLikelihood>
<n1:Formula/>
</n1:decreasesLikelihood>
<n1:independentProbability>
<n1:Formula/>
</n1:independentProbability>
<n1:increasesLikelihood>
<n1:Formula/>
</n1:increasesLikelihood>
<n1:modalAttribute>
<n1:NormativeAttribute/>
</n1:modalAttribute>
<n1:entails>
<n1:Formula/>
</n1:entails>
<n1:true>
<n1:TruthValue/>
</n1:true>
</n1:Formula>
</n1:holdsDuring>
</n1:TimePoint>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:starts>
<n1:finishes>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint>
<n1:before>
<n1:TimePoint/>
</n1:before>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimePoint>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:during>
<n1:EndFn>
<n1:TimePoint>
<n1:before>
<n1:TimePoint/>
</n1:before>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimePoint>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula>
<n1:ProbabilityFn>
<n1:RealNumber/>
</n1:ProbabilityFn>
<n1:decreasesLikelihood>
<n1:Formula/>
</n1:decreasesLikelihood>
<n1:independentProbability>
<n1:Formula/>
</n1:independentProbability>
<n1:increasesLikelihood>
<n1:Formula/>
</n1:increasesLikelihood>
<n1:modalAttribute>
<n1:NormativeAttribute/>
</n1:modalAttribute>
<n1:entails>
<n1:Formula/>
</n1:entails>
<n1:true>
<n1:TruthValue/>
</n1:true>
</n1:Formula>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:during>
<n1:EndFn>
<n1:TimePoint>
<n1:before>
<n1:TimePoint>
<n1:before>
<n1:TimePoint/>
</n1:before>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimePoint>
</n1:before>
<n1:FutureFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula>
<n1:ProbabilityFn>
<n1:RealNumber/>
</n1:ProbabilityFn>
<n1:decreasesLikelihood>
<n1:Formula/>
</n1:decreasesLikelihood>
<n1:independentProbability>
<n1:Formula/>
</n1:independentProbability>
<n1:increasesLikelihood>
<n1:Formula/>
</n1:increasesLikelihood>
<n1:modalAttribute>
<n1:NormativeAttribute/>
</n1:modalAttribute>
<n1:entails>
<n1:Formula/>
</n1:entails>
<n1:true>
<n1:TruthValue/>
</n1:true>
</n1:Formula>
</n1:holdsDuring>
</n1:TimePoint>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:starts>
<n1:finishes>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint>
<n1:before>
<n1:TimePoint/>
</n1:before>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimePoint>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:during>
<n1:EndFn>
<n1:TimePoint>
<n1:before>
<n1:TimePoint/>
</n1:before>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimePoint>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula>
<n1:ProbabilityFn>
<n1:RealNumber/>
</n1:ProbabilityFn>
<n1:decreasesLikelihood>
<n1:Formula/>
</n1:decreasesLikelihood>
<n1:independentProbability>
<n1:Formula/>
</n1:independentProbability>
<n1:increasesLikelihood>
<n1:Formula/>
</n1:increasesLikelihood>
<n1:modalAttribute>
<n1:NormativeAttribute/>
</n1:modalAttribute>
<n1:entails>
<n1:Formula/>
</n1:entails>
<n1:true>
<n1:TruthValue/>
</n1:true>
</n1:Formula>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:starts>
<n1:finishes>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint>
<n1:before>
<n1:TimePoint/>
</n1:before>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimePoint>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:during>
<n1:EndFn>
<n1:TimePoint>
<n1:before>
<n1:TimePoint/>
</n1:before>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimePoint>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval>
<n1:starts>
<n1:TimeInterval/>
</n1:starts>
<n1:finishes>
<n1:TimeInterval/>
</n1:finishes>
<n1:BeginFn>
<n1:TimePoint/>
</n1:BeginFn>
<n1:duration>
<n1:TimeDuration/>
</n1:duration>
<n1:during>
<n1:TimeInterval/>
</n1:during>
<n1:EndFn>
<n1:TimePoint/>
</n1:EndFn>
<n1:earlier>
<n1:TimeInterval/>
</n1:earlier>
<n1:meetsTemporally>
<n1:TimeInterval/>
</n1:meetsTemporally>
<n1:FutureFn>
<n1:TimeInterval/>
</n1:FutureFn>
<n1:ImmediatePastFn>
<n1:TimeInterval/>
</n1:ImmediatePastFn>
<n1:PastFn>
<n1:TimeInterval/>
</n1:PastFn>
<n1:ImmediateFutureFn>
<n1:TimeInterval/>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula/>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:ImmediateFutureFn>
<n1:holdsDuring>
<n1:Formula>
<n1:ProbabilityFn>
<n1:RealNumber/>
</n1:ProbabilityFn>
<n1:decreasesLikelihood>
<n1:Formula/>
</n1:decreasesLikelihood>
<n1:independentProbability>
<n1:Formula/>
</n1:independentProbability>
<n1:increasesLikelihood>
<n1:Formula/>
</n1:increasesLikelihood>
<n1:modalAttribute>
<n1:NormativeAttribute/>
</n1:modalAttribute>
<n1:entails>
<n1:Formula/>
</n1:entails>
<n1:true>
<n1:TruthValue/>
</n1:true>
</n1:Formula>
</n1:holdsDuring>
</n1:TimeInterval>
</n1:meetsTemporally>
</n1:Year>
</rdf:RDF>
</xsl:template>
</xsl:transform>
